import { AiAgentMode, AiAgentApprovalPolicy } from '../types';

interface AgentSeedConfig {
  number: number;
  name: string;
  role: string;
  category: string;
  purpose: string;
  tools: string[];
  scope: string;
  policy?: AiAgentApprovalPolicy;
  icon?: string;
  cron?: string;
  budgetUsd?: number;
}

const CONTROLLED_WORKFLOW_STEPS = [
  'MONITOR',
  'DETECT',
  'ANALYZE',
  'PLAN',
  'IMPLEMENT',
  'TEST',
  'BUILD',
  'PREVIEW',
  'APPROVAL',
  'DEPLOY',
  'HEALTH CHECK',
  'AUDIT',
];

const RAW_AGENT_SPECS: AgentSeedConfig[] = [
  // 1-8: Core AI / Orchestration
  { number: 1, name: 'Master AI Agent', role: 'Coordinates all agents and tasks', category: 'Core AI / Orchestration', purpose: 'Coordinates all agents, multi-agent task planning, resource allocation, and plan synthesis.', tools: ['coordinate_agents', 'create_task', 'synthesize_plan', 'enforce_policy', 'escalate_approval'], scope: 'Global System Orchestration', policy: 'CRITICAL_ONLY', icon: 'Bot' },
  { number: 2, name: 'AI Orchestrator', role: 'Routes tasks to the correct agent', category: 'Core AI / Orchestration', purpose: 'Routes tasks to the correct agent based on capabilities and workload.', tools: ['route_task', 'load_balance', 'inspect_capabilities'], scope: 'Task Dispatch & Routing', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Cpu' },
  { number: 3, name: 'Research Agent', role: 'Researches approved information sources', category: 'Core AI / Orchestration', purpose: 'Researches approved information sources for specifications, guidelines, and verified data.', tools: ['search_approved_sources', 'extract_facts', 'validate_citations'], scope: 'Authorized Research Domains', policy: 'READ_ONLY_SUGGEST', icon: 'Search' },
  { number: 4, name: 'Search Agent', role: 'Searches authorized web/database sources', category: 'Core AI / Orchestration', purpose: 'Searches authorized web and database sources without leaking proprietary context.', tools: ['query_database', 'vector_search', 'filter_results'], scope: 'Authorized Indexes & Schemas', policy: 'READ_ONLY_SUGGEST', icon: 'Search' },
  { number: 5, name: 'Decision Agent', role: 'Evaluates technical options without bypassing rules', category: 'Core AI / Orchestration', purpose: 'Evaluates available technical options without bypassing approval rules.', tools: ['evaluate_tradeoffs', 'risk_assessment', 'policy_check'], scope: 'Decision Matrix Analysis', policy: 'CRITICAL_ONLY', icon: 'Sliders' },
  { number: 6, name: 'Task Planner Agent', role: 'Converts requests into executable task plans', category: 'Core AI / Orchestration', purpose: 'Converts requests into executable task plans with dependency tracking.', tools: ['decompose_goals', 'estimate_runtime', 'build_dag'], scope: 'Task Planning & Queues', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Layers' },
  { number: 7, name: 'Automation Agent', role: 'Manages approved recurring workflows', category: 'Core AI / Orchestration', purpose: 'Manages approved recurring workflows, monitors cron triggers, and executes automated jobs.', tools: ['run_cron_job', 'inspect_queue', 'retry_handler'], scope: 'Automated System Schedules', policy: 'CRITICAL_ONLY', icon: 'Clock', cron: '0 * * * *' },
  { number: 8, name: 'Memory/Context Agent', role: 'Manages authorized project context', category: 'Core AI / Orchestration', purpose: 'Manages authorized project context, vector embeddings, and session state.', tools: ['retrieve_context', 'compact_memory', 'sanitize_secrets'], scope: 'Context State & Semantic Store', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Terminal' },

  // 9-23: Website / Product
  { number: 9, name: 'Website Manager Agent', role: 'Coordinates website structure and settings', category: 'Website / Product', purpose: 'Coordinates website structure, page layouts, navigation menus, and site configuration.', tools: ['update_layout', 'manage_nav', 'inspect_routes'], scope: 'Website Navigation & Config', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Globe' },
  { number: 10, name: 'Page Builder Agent', role: 'Assembles landing pages and dynamic views', category: 'Website / Product', purpose: 'Assembles landing pages and dynamic views using existing component systems.', tools: ['assemble_page', 'reorder_sections', 'bind_data'], scope: 'src/pages/*', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Layers' },
  { number: 11, name: 'UI/UX Agent', role: 'Maintains user experience fidelity', category: 'Website / Product', purpose: 'Maintains user experience fidelity, interaction patterns, and visual hierarchy.', tools: ['audit_ui_tokens', 'verify_contrast', 'inspect_spacing'], scope: 'UI Components & Interaction', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Palette' },
  { number: 12, name: 'Design System Agent', role: 'Enforces brand typography and color palette', category: 'Website / Product', purpose: 'Enforces brand typography, dark luxury palette (Syne, Crimson, Gold), and CSS tokens.', tools: ['validate_tokens', 'sync_theme', 'enforce_palette'], scope: 'Design System & Stylesheets', policy: 'CRITICAL_ONLY', icon: 'Palette' },
  { number: 13, name: 'Frontend Agent', role: 'Builds responsive React TypeScript interfaces', category: 'Website / Product', purpose: 'Builds responsive React TypeScript interfaces adhering to modern web standards.', tools: ['generate_component', 'hook_management', 'state_binding'], scope: 'src/components/*', policy: 'CRITICAL_ONLY', icon: 'Code2' },
  { number: 14, name: 'Backend Agent', role: 'Maintains client data layer and services', category: 'Website / Product', purpose: 'Maintains client data layer, local storage services, and API proxy connectors.', tools: ['service_worker', 'db_service_sync', 'event_bus_handler'], scope: 'src/services/*', policy: 'CRITICAL_ONLY', icon: 'Terminal' },
  { number: 15, name: 'Feature Builder Agent', role: 'Transforms requirements into modular features', category: 'Website / Product', purpose: 'Transforms requirements into modular features with zero tech debt.', tools: ['feature_scaffold', 'wire_routes', 'spec_verification'], scope: 'Feature Implementations', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Sparkles' },
  { number: 16, name: 'Component Agent', role: 'Creates atomic and molecular UI components', category: 'Website / Product', purpose: 'Creates atomic and molecular UI components with strictly typed interfaces.', tools: ['build_atom', 'prop_typing', 'aria_attributes'], scope: 'src/components/ui/*', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Layers' },
  { number: 17, name: 'Responsive Design Agent', role: 'Audits layouts across desktop, tablet, and mobile', category: 'Website / Product', purpose: 'Audits layouts across desktop (1920px+), tablet, and mobile viewport breakpoints.', tools: ['breakpoint_test', 'grid_collapse_check', 'touch_target_check'], scope: 'Layout Responsive Breakpoints', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Globe' },
  { number: 18, name: 'Accessibility Agent', role: 'Enforces WCAG 2.1 AA accessibility standards', category: 'Website / Product', purpose: 'Enforces WCAG 2.1 AA accessibility standards, keyboard nav, and screen reader labels.', tools: ['aria_audit', 'keyboard_focus_check', 'color_contrast_ratio'], scope: 'DOM Accessibility & ARIA', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },
  { number: 19, name: 'Mobile Optimization Agent', role: 'Optimizes touch gestures and mobile rendering', category: 'Website / Product', purpose: 'Optimizes touch gestures, mobile drawer menus, and small-screen rendering performance.', tools: ['touch_latency_audit', 'mobile_fps_monitor', 'viewport_containment'], scope: 'Mobile Views & Touch UI', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity' },
  { number: 20, name: 'Desktop/Web Optimization Agent', role: 'Optimizes widescreen desktop layouts (1280px-2560px+)', category: 'Website / Product', purpose: 'Optimizes widescreen desktop layouts (1280px to 2560px+), multi-column grids, and cinematic banners.', tools: ['wide_grid_balance', 'desktop_nav_audit', 'canvas_scaling'], scope: 'Desktop Multi-Column Grids', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Globe' },
  { number: 21, name: 'SEO Agent', role: 'Maintains metadata, OpenGraph cards, and schema', category: 'Website / Product', purpose: 'Maintains metadata, OpenGraph cards, Twitter cards, and JSON-LD schema.', tools: ['meta_tag_sync', 'generate_sitemap', 'schema_ld_audit'], scope: 'HTML Head & Social Meta', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 22, name: 'Content Agent', role: 'Curates official artist press copy and lyrics', category: 'Website / Product', purpose: 'Curates official artist press copy, bios, lyrics, and news announcements.', tools: ['validate_spelling', 'tone_check', 'format_lyrics'], scope: 'Site Content & Editorial Text', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 23, name: 'Media Agent', role: 'Manages images, posters, artwork, and banners', category: 'Website / Product', purpose: 'Manages images, posters, album artwork, and banners with optimized webp formats.', tools: ['aspect_ratio_verify', 'optimize_image', 'alt_text_verify'], scope: 'Media Assets & Galleries', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Camera' },

  // 24-37: Code / Development
  { number: 24, name: 'Code Agent', role: 'Writes clean, modular TypeScript code', category: 'Code / Development', purpose: 'Writes clean, modular TypeScript code adhering to strict types and React conventions.', tools: ['write_code', 'search_code', 'refactor_syntax'], scope: 'src/**/*.{ts,tsx}', policy: 'CRITICAL_ONLY', icon: 'Code2' },
  { number: 25, name: 'Code Review Agent', role: 'Performs automated code reviews and diff analysis', category: 'Code / Development', purpose: 'Performs automated code reviews, diff analysis, and architectural compliance checks.', tools: ['analyze_ast_diff', 'check_anti_patterns', 'flag_regressions'], scope: 'Code Diffs & Pull Requests', policy: 'READ_ONLY_SUGGEST', icon: 'CheckCircle2' },
  { number: 26, name: 'Bug Fix Agent', role: 'Diagnoses runtime errors and generates patches', category: 'Code / Development', purpose: 'Diagnoses runtime errors, investigates stack traces, and generates targeted bug patches.', tools: ['trace_error_stack', 'reproduce_bug', 'generate_patch'], scope: 'Bug Diagnostics & Hotfixes', policy: 'CRITICAL_ONLY', icon: 'Wrench' },
  { number: 27, name: 'Refactoring Agent', role: 'Simplifies complex functions and reduces duplication', category: 'Code / Development', purpose: 'Simplifies complex functions, extracts reusable hooks, and eliminates duplicate logic.', tools: ['extract_hook', 'inline_dead_code', 'simplify_conditionals'], scope: 'Refactoring Workspace', policy: 'CRITICAL_ONLY', icon: 'Code2' },
  { number: 28, name: 'Dependency Agent', role: 'Audits npm dependencies and version conflicts', category: 'Code / Development', purpose: 'Audits npm dependencies, prevents vulnerability bloat, and resolves package conflicts.', tools: ['audit_package_json', 'check_peer_deps', 'verify_bundle_size'], scope: 'package.json & lockfiles', policy: 'CRITICAL_ONLY', icon: 'Terminal' },
  { number: 29, name: 'API Agent', role: 'Manages REST endpoints, mocks, and payload contracts', category: 'Code / Development', purpose: 'Manages REST endpoints, API contracts, TypeScript DTOs, and error responses.', tools: ['validate_schema', 'generate_dto', 'mock_endpoint'], scope: 'API Interfaces & Proxies', policy: 'CRITICAL_ONLY', icon: 'Zap' },
  { number: 30, name: 'Database Agent', role: 'Governs database schemas and persistence operations', category: 'Code / Development', purpose: 'Governs database schemas, state collections, indexes, and persistence operations.', tools: ['schema_migration', 'validate_constraints', 'seed_data'], scope: 'src/services/db.ts & Collections', policy: 'CRITICAL_ONLY', icon: 'Database' },
  { number: 31, name: 'Database Performance Agent', role: 'Monitors query latency and local storage quota', category: 'Code / Development', purpose: 'Monitors query latency, indexing efficiency, and local storage memory quotas.', tools: ['profile_query_latency', 'check_storage_quota', 'optimize_indexes'], scope: 'Database Performance Profiling', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity' },
  { number: 32, name: 'Migration Agent', role: 'Executes schema migrations safely with rollback points', category: 'Code / Development', purpose: 'Executes schema migrations safely with automatic snapshots and rollback checkpoints.', tools: ['create_snapshot', 'apply_migration_plan', 'rollback_to_snapshot'], scope: 'Schema Migrations & Rollbacks', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'History' },
  { number: 33, name: 'Caching Agent', role: 'Configures in-memory and HTTP cache policies', category: 'Code / Development', purpose: 'Configures in-memory and client-side caching policies for high performance.', tools: ['manage_lru_cache', 'invalidate_keys', 'set_ttl_policy'], scope: 'Cache Strategies & Memory', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Cpu' },
  { number: 34, name: 'Realtime/WebSocket Agent', role: 'Manages event bus broadcasting and subscriptions', category: 'Code / Development', purpose: 'Manages event bus broadcasting, window event listeners, and realtime synchronization.', tools: ['event_bus_dispatch', 'listener_cleanup_audit', 'reconnect_manager'], scope: 'Realtime Bus & Event Listeners', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity' },
  { number: 35, name: 'Integration Agent', role: 'Connects external audio, payment, and video platforms', category: 'Code / Development', purpose: 'Connects verified external streaming links, payment gateways, and social platforms.', tools: ['verify_webhook_signature', 'sanitize_redirects', 'payload_mapper'], scope: 'Integrations & Webhooks', policy: 'CRITICAL_ONLY', icon: 'Sliders' },
  { number: 36, name: 'Environment Configuration Agent', role: 'Manages public environment variables and defaults', category: 'Code / Development', purpose: 'Manages public environment variables, build flags, and dev/prod mode switches.', tools: ['validate_env_vars', 'mask_sensitive_flags', 'sync_env_example'], scope: '.env.example & Runtime Config', policy: 'CRITICAL_ONLY', icon: 'Lock' },
  { number: 37, name: 'Documentation Agent', role: 'Maintains API docs, user guides, and changelogs', category: 'Code / Development', purpose: 'Maintains internal architecture documentation, API specifications, and release notes.', tools: ['generate_markdown_doc', 'sync_changelog', 'document_interface'], scope: 'Documentation & Architecture Notes', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },

  // 38-48: Testing / Quality
  { number: 38, name: 'QA Agent', role: 'Directs overall quality assurance strategy', category: 'Testing / Quality', purpose: 'Directs overall quality assurance strategy, test matrix execution, and pass/fail thresholds.', tools: ['run_test_suite', 'evaluate_pass_rate', 'gate_release'], scope: 'QA Test Orchestration', policy: 'CRITICAL_ONLY', icon: 'CheckCircle2' },
  { number: 39, name: 'Test Agent', role: 'Executes automated test suites across modules', category: 'Testing / Quality', purpose: 'Executes automated test suites across React components and database functions.', tools: ['execute_tests', 'report_failures', 'generate_fixtures'], scope: 'Test Suites & Assertions', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },
  { number: 40, name: 'Unit Test Agent', role: 'Generates isolated unit tests for functions and hooks', category: 'Testing / Quality', purpose: 'Generates isolated unit tests for utilities, custom hooks, and mathematical models.', tools: ['scaffold_unit_test', 'mock_dependencies', 'assert_pure_output'], scope: 'Unit Tests & Coverage', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },
  { number: 41, name: 'Integration Test Agent', role: 'Tests cross-component workflows and event buses', category: 'Testing / Quality', purpose: 'Tests cross-component workflows, event buses, and database state mutations.', tools: ['simulate_user_journey', 'verify_state_transitions', 'assert_event_emission'], scope: 'Cross-Component Integration', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Layers' },
  { number: 42, name: 'E2E Test Agent', role: 'Simulates end-to-end browser user scenarios', category: 'Testing / Quality', purpose: 'Simulates end-to-end browser user scenarios like audio playback, checkout, and search.', tools: ['headless_flow_run', 'snapshot_dom', 'verify_checkout_flow'], scope: 'End-to-End User Journeys', policy: 'CRITICAL_ONLY', icon: 'Play' },
  { number: 43, name: 'Regression Test Agent', role: 'Detects unexpected regressions in modified files', category: 'Testing / Quality', purpose: 'Detects unexpected regressions in modified files prior to build and deployment.', tools: ['compare_snapshots', 'detect_side_effects', 'verify_backwards_compat'], scope: 'Regression Verification', policy: 'CRITICAL_ONLY', icon: 'History' },
  { number: 44, name: 'Performance Test Agent', role: 'Measures Core Web Vitals, FCP, LCP, and CLS', category: 'Testing / Quality', purpose: 'Measures Core Web Vitals, First Contentful Paint, LCP, and Cumulative Layout Shift.', tools: ['measure_web_vitals', 'profile_bundle', 'detect_heavy_dom'], scope: 'Performance Benchmarks', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Flame' },
  { number: 45, name: 'Security Test Agent', role: 'Performs automated penetration and XSS vulnerability testing', category: 'Testing / Quality', purpose: 'Performs automated penetration testing, XSS input scrubbing, and CSRF audits.', tools: ['xss_fuzzing', 'csp_eval', 'input_sanitization_test'], scope: 'Security Vulnerability Probing', policy: 'CRITICAL_ONLY', icon: 'ShieldAlert' },
  { number: 46, name: 'Accessibility Test Agent', role: 'Executes automated aXe accessibility tests', category: 'Testing / Quality', purpose: 'Executes automated aXe accessibility tests and contrast verification.', tools: ['axe_core_audit', 'screen_reader_simulation', 'tab_order_check'], scope: 'Automated A11y Suite', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },
  { number: 47, name: 'Compatibility Test Agent', role: 'Verifies cross-browser and platform parity', category: 'Testing / Quality', purpose: 'Verifies cross-browser rendering parity across Chromium, Safari, Firefox, and WebKit.', tools: ['css_prefix_check', 'detect_unsupported_apis', 'poly_fill_audit'], scope: 'Browser Compatibility Matrix', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Globe' },
  { number: 48, name: 'Release QA Agent', role: 'Provides final sign-off gate before staging/prod', category: 'Testing / Quality', purpose: 'Provides final sign-off gate before deployment: verifies tests, builds, and linting.', tools: ['generate_qa_report', 'verify_zero_errors', 'certify_release'], scope: 'Release Gating & Certification', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'ShieldCheck' },

  // 49-60: Security
  { number: 49, name: 'Security Agent', role: 'Oversees overall platform security and policies', category: 'Security', purpose: 'Oversees overall platform security, policy enforcement, and defense-in-depth posture.', tools: ['audit_security_posture', 'enforce_csp', 'log_security_alert'], scope: 'Global Security Architecture', policy: 'CRITICAL_ONLY', icon: 'ShieldAlert' },
  { number: 50, name: 'Authentication Security Agent', role: 'Guards login, MFA, and credential validation', category: 'Security', purpose: 'Guards login, MFA, and credential validation. Enforces password policies.', tools: ['verify_mfa_token', 'detect_brute_force', 'hash_timing_protect'], scope: 'Authentication Engine', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Lock' },
  { number: 51, name: 'Authorization/RBAC Agent', role: 'Enforces role-based access control rules', category: 'Security', purpose: 'Enforces role-based access control (Admin, Artist, Fan, Guest) on all routes and actions.', tools: ['check_permission_grant', 'validate_role_matrix', 'deny_unauthorized_access'], scope: 'RBAC Enforcement Matrix', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'ShieldCheck' },
  { number: 52, name: 'Session Security Agent', role: 'Manages secure session tokens and idle timeouts', category: 'Security', purpose: 'Manages secure session tokens, idle timeouts, and cryptographic token revocation.', tools: ['revoke_session', 'enforce_idle_timeout', 'detect_token_theft'], scope: 'User Session Lifetime', policy: 'CRITICAL_ONLY', icon: 'Clock' },
  { number: 53, name: 'API Security Agent', role: 'Protects internal endpoints against abuse and injection', category: 'Security', purpose: 'Protects internal endpoints against abuse, SQLi/NoSQLi, and malformed JSON payloads.', tools: ['sanitize_payload', 'validate_request_signature', 'block_injection'], scope: 'API Gateways & Endpoints', policy: 'CRITICAL_ONLY', icon: 'ShieldAlert' },
  { number: 54, name: 'Dependency Security Agent', role: 'Scans for CVEs and malicious supply chain packages', category: 'Security', purpose: 'Scans for CVEs and malicious supply chain packages in third-party libraries.', tools: ['npm_audit_scan', 'advisory_lookup', 'isolate_dependency'], scope: 'Third-Party Package Security', policy: 'CRITICAL_ONLY', icon: 'Terminal' },
  { number: 55, name: 'Vulnerability Agent', role: 'Performs proactive zero-day and code flaw sweeps', category: 'Security', purpose: 'Performs proactive sweeps for secrets leaks, prototype pollution, and memory leaks.', tools: ['scan_code_vulnerabilities', 'flag_unsafe_eval', 'audit_regex_dos'], scope: 'Static Code Analysis', policy: 'CRITICAL_ONLY', icon: 'AlertTriangle' },
  { number: 56, name: 'Privacy Agent', role: 'Protects user PII, GDPR compliance, and consent', category: 'Security', purpose: 'Protects user PII, GDPR/CCPA compliance, consent logging, and data anonymization.', tools: ['scrub_pii_from_logs', 'handle_data_erasure', 'audit_cookie_consent'], scope: 'Privacy Safeguards & Consent', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Lock' },
  { number: 57, name: 'Audit Agent', role: 'Maintains tamper-proof security audit log streams', category: 'Security', purpose: 'Maintains tamper-proof security audit log streams for administrative and financial events.', tools: ['write_audit_entry', 'verify_log_hash_chain', 'export_audit_archive'], scope: 'Audit Logs & Immutability', policy: 'READ_ONLY_SUGGEST', icon: 'FileText' },
  { number: 58, name: 'Compliance Agent', role: 'Verifies compliance with legal, financial, and music rules', category: 'Security', purpose: 'Verifies compliance with legal, financial, and digital music distribution regulations.', tools: ['verify_non_cash_policy', 'check_disclaimer_presence', 'assert_tax_compliance'], scope: 'Platform Regulatory Compliance', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'ShieldCheck' },
  { number: 59, name: 'Secrets Protection Agent', role: 'Guarantees API keys, credentials, and tokens never leak', category: 'Security', purpose: 'Guarantees API keys, database credentials, server passwords, session tokens, private keys, and encryption keys are NEVER exposed through UI, logs, source code, or AI context.', tools: ['intercept_secret_leak', 'redact_credentials', 'enforce_zero_leak_boundary'], scope: 'Global Zero-Leak Secrets Boundary', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Lock' },
  { number: 60, name: 'Abuse/Rate-Limit Agent', role: 'Throttles brute force requests and DDoS spikes', category: 'Security', purpose: 'Throttles brute force requests, mitigates bot traffic, and enforces sliding window limits.', tools: ['enforce_ip_rate_limit', 'challenge_suspicious_traffic', 'block_offending_ip'], scope: 'Traffic Limiting & Anti-Abuse', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'ShieldAlert' },

  // 61-76: Build / Deployment / Infrastructure
  { number: 61, name: 'Build Agent', role: 'Executes clean TypeScript compilation and bundling', category: 'Build / Deployment / Infrastructure', purpose: 'Executes clean TypeScript compilation and Vite bundling with zero fatal errors.', tools: ['run_build', 'inspect_build_stats', 'purge_build_cache'], scope: 'Vite & TypeScript Compilers', policy: 'CRITICAL_ONLY', icon: 'Terminal' },
  { number: 62, name: 'Deployment Agent', role: 'Manages production staging and release pipelines', category: 'Build / Deployment / Infrastructure', purpose: 'Manages production release pipelines subject to human owner authorization.', tools: ['deploy_bundle', 'verify_checksums', 'activate_release'], scope: 'Deployment Pipelines', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Flame' },
  { number: 63, name: 'Preview Environment Agent', role: 'Spins up isolated preview environments for feature testing', category: 'Build / Deployment / Infrastructure', purpose: 'Spins up isolated preview environments for safe feature verification and review.', tools: ['generate_preview_url', 'mount_sandbox_storage', 'tear_down_preview'], scope: 'Ephemeral Preview Sandboxes', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Play' },
  { number: 64, name: 'Infrastructure Agent', role: 'Monitors serverless containers, ports, and dev servers', category: 'Build / Deployment / Infrastructure', purpose: 'Monitors serverless containers, dev servers on port 3000, and node runtimes.', tools: ['check_node_health', 'monitor_memory_usage', 'verify_port_bindings'], scope: 'Dev Server & Container Env', policy: 'CRITICAL_ONLY', icon: 'Cpu' },
  { number: 65, name: 'Domain Agent', role: 'Configures custom domains, DNS records, and CNAMEs', category: 'Build / Deployment / Infrastructure', purpose: 'Configures custom artist domains, DNS records, CNAMEs, and routing headers.', tools: ['query_dns_records', 'verify_domain_ownership', 'update_cname_routing'], scope: 'DNS & Custom Domains', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Globe' },
  { number: 66, name: 'SSL/TLS Agent', role: 'Monitors certificate validity and HTTPS enforcement', category: 'Build / Deployment / Infrastructure', purpose: 'Monitors SSL/TLS certificate validity, HSTS headers, and HTTPS enforcement.', tools: ['check_cert_expiry', 'enforce_hsts', 'audit_tls_ciphers'], scope: 'HTTPS & TLS Certs', policy: 'CRITICAL_ONLY', icon: 'Lock' },
  { number: 67, name: 'Cloud Storage Agent', role: 'Manages assets, CDNs, media buckets, and uploads', category: 'Build / Deployment / Infrastructure', purpose: 'Manages media asset storage, cache headers, CDN distribution, and upload quotas.', tools: ['manage_bucket', 'set_cors_headers', 'purge_cdn_cache'], scope: 'Cloud Storage & CDN', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Database' },
  { number: 68, name: 'Queue/Worker Agent', role: 'Processes background asynchronous jobs and retries', category: 'Build / Deployment / Infrastructure', purpose: 'Processes background asynchronous jobs, task queues, and dead-letter retries.', tools: ['drain_queue', 'enqueue_job', 'handle_dead_letter'], scope: 'Background Task Queues', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Layers' },
  { number: 69, name: 'Monitoring Agent', role: 'Maintains 24/7 telemetry on portal health and uptime', category: 'Build / Deployment / Infrastructure', purpose: 'Maintains 24/7 telemetry on portal health, API response times, and anomaly detection.', tools: ['poll_healthcheck', 'record_telemetry_metric', 'trigger_alert'], scope: '24/7 Health Monitoring', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity', cron: '*/5 * * * *' },
  { number: 70, name: 'Error Agent', role: 'Captures unhandled exceptions and aggregates crash reports', category: 'Build / Deployment / Infrastructure', purpose: 'Captures unhandled exceptions, aggregates error signatures, and deduplicates logs.', tools: ['capture_exception', 'aggregate_error_groups', 'generate_error_report'], scope: 'Error Aggregation & Telemetry', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'AlertTriangle' },
  { number: 71, name: 'Log Agent', role: 'Streams structured logs with severity and search indexing', category: 'Build / Deployment / Infrastructure', purpose: 'Streams structured logs with timestamp, severity, task context, and fast indexing.', tools: ['stream_log', 'filter_logs', 'export_log_archive'], scope: 'System Log Streams', policy: 'READ_ONLY_SUGGEST', icon: 'Terminal' },
  { number: 72, name: 'Performance Agent', role: 'Profiles memory leaks, CPU spikes, and renders', category: 'Build / Deployment / Infrastructure', purpose: 'Profiles memory leaks, CPU spikes, render overhead, and bundle weight.', tools: ['profile_cpu', 'detect_memory_leak', 'bundle_treemap_analysis'], scope: 'Runtime Performance Diagnostics', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Flame' },
  { number: 73, name: 'Uptime/Health Agent', role: 'Performs external heartbeat checks and failover triggers', category: 'Build / Deployment / Infrastructure', purpose: 'Performs external heartbeat checks, status page updates, and latency measurements.', tools: ['ping_heartbeat', 'update_status_page', 'calculate_sla_uptime'], scope: 'Uptime & SLA Tracking', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity' },
  { number: 74, name: 'Backup Agent', role: 'Creates automated local and cloud database snapshots', category: 'Build / Deployment / Infrastructure', purpose: 'Creates automated local and cloud database snapshots with cryptographic integrity.', tools: ['create_db_backup', 'verify_backup_checksum', 'list_backups'], scope: 'Database Snapshots & Archives', policy: 'CRITICAL_ONLY', cron: '0 0 * * *' },
  { number: 75, name: 'Disaster Recovery Agent', role: 'Manages disaster recovery runbooks and failovers', category: 'Build / Deployment / Infrastructure', purpose: 'Manages disaster recovery runbooks, cold-start rehydration, and state restoration.', tools: ['execute_dr_plan', 'validate_data_recovery', 'verify_state_integrity'], scope: 'Disaster Recovery & Redundancy', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'History' },
  { number: 76, name: 'Rollback Agent', role: 'Instantly rolls back faulty releases to last known-good state', category: 'Build / Deployment / Infrastructure', purpose: 'Instantly rolls back faulty releases to the last known-good production snapshot.', tools: ['execute_rollback', 'restore_previous_bundle', 'notify_emergency_team'], scope: 'Production Rollback Mechanism', policy: 'CRITICAL_ONLY', icon: 'History' },

  // 77-90: Music / Artist
  { number: 77, name: 'Music Agent', role: 'Governs audio player, tracks, waveforms, and streaming links', category: 'Music / Artist', purpose: 'Governs audio player engine, waveform analysis, stream URLs, and track metadata.', tools: ['update_audio_catalog', 'generate_waveform_peaks', 'test_stream_audio'], scope: 'Audio Player & Catalog Engine', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Disc' },
  { number: 78, name: 'Artist Profile Agent', role: 'Maintains official artist biography, photos, and socials', category: 'Music / Artist', purpose: 'Maintains official artist biography, press headshots, badges, and verified accounts.', tools: ['update_artist_bio', 'sync_social_handles', 'manage_press_photos'], scope: 'Artist Identity & Bio', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Bot' },
  { number: 79, name: 'Release Management Agent', role: 'Coordinates album, EP, and single release schedules', category: 'Music / Artist', purpose: 'Coordinates album, EP, and single release schedules, pre-saves, and launch clocks.', tools: ['schedule_release', 'configure_presave', 'publish_release_live'], scope: 'Release Calendars & Lifecycles', policy: 'CRITICAL_ONLY', icon: 'Sparkles' },
  { number: 80, name: 'Metadata Agent', role: 'Validates ID3 tags, lyrics, genre classifications, and bpm', category: 'Music / Artist', purpose: 'Validates ID3 tags, synchronized lyrics, genre classifications, key, and tempo.', tools: ['validate_id3_tags', 'format_lyrics_timestamps', 'classify_bpm_key'], scope: 'Music Track Metadata', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 81, name: 'Artwork Compliance Agent', role: 'Enforces 3000x3000px square cover art compliance', category: 'Music / Artist', purpose: 'Enforces DSP artwork guidelines: 3000x3000px square, 300dpi, no blurry text or trademarks.', tools: ['validate_artwork_dimensions', 'verify_aspect_ratio_1x1', 'inspect_dsp_compliance'], scope: 'Artwork Standards & DSP Rules', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Camera' },
  { number: 82, name: 'Credits Agent', role: 'Maintains songwriters, producers, mix/master engineers', category: 'Music / Artist', purpose: 'Maintains accurate songwriting splits, producers, featured artists, and engineers.', tools: ['record_song_credits', 'verify_ipi_cae_numbers', 'generate_liner_notes'], scope: 'Songwriting & Master Credits', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 83, name: 'ISRC/UPC Metadata Agent', role: 'Validates international standard recording codes and barcodes', category: 'Music / Artist', purpose: 'Validates standard 12-character ISRC recording codes and 12/13-digit UPC/EAN barcodes.', tools: ['validate_isrc_format', 'verify_upc_checksum', 'assign_identifier'], scope: 'ISRC & UPC Registry Codes', policy: 'CRITICAL_ONLY', icon: 'ShieldCheck' },
  { number: 84, name: 'Distribution Agent', role: 'Integrates with Ditto, DistroKid, and DSP dispatch channels', category: 'Music / Artist', purpose: 'Integrates with digital distributors, prepares DDEX payloads, and monitors feeds.', tools: ['generate_distribution_manifest', 'check_dsp_feed_status', 'track_delivery_status'], scope: 'Distribution Pipelines & DSPs', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Sliders' },
  { number: 85, name: 'Release Validation Agent', role: 'Conducts pre-distribution checks for lossless audio and tags', category: 'Music / Artist', purpose: 'Conducts pre-distribution checks: 24-bit 44.1kHz+ WAV, uncompressed tags, and clearances.', tools: ['verify_lossless_audio', 'check_explicit_tag', 'validate_title_capitalization'], scope: 'Pre-Distribution Validation Gate', policy: 'CRITICAL_ONLY', icon: 'CheckCircle2' },
  { number: 86, name: 'Music Catalog Agent', role: 'Maintains discography indexing and search tags', category: 'Music / Artist', purpose: 'Maintains discography indexing, track search tags, mood classifications, and plays.', tools: ['index_discography', 'search_tracks_catalog', 'update_track_tags'], scope: 'Discography Database Index', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Disc' },
  { number: 87, name: 'Royalty Information Agent', role: 'Tracks 85/15 artist/label revenue shares and mechanicals', category: 'Music / Artist', purpose: 'Calculates contractual 85/15 revenue share splits, mechanical royalties, and payouts.', tools: ['compute_revenue_split', 'generate_royalty_statement', 'audit_earnings_pool'], scope: 'Contractual Royalty Calculation', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'BarChart3' },
  { number: 88, name: 'Music Analytics Agent', role: 'Analyzes streams, saves, playlist adds, and listener charts', category: 'Music / Artist', purpose: 'Analyzes cross-platform stream trends, Spotify/Apple playlist adds, and listener geos.', tools: ['aggregate_stream_counts', 'chart_listener_demographics', 'compute_trend_velocity'], scope: 'Streaming Analytics Data', policy: 'READ_ONLY_SUGGEST', icon: 'BarChart3' },
  { number: 89, name: 'Playlist/Platform Metadata Agent', role: 'Generates editorial pitch summaries and playlist tags', category: 'Music / Artist', purpose: 'Generates editorial playlist pitch summaries, sub-genre tags, and mood classifications.', tools: ['draft_editorial_pitch', 'tag_playlist_vibes', 'sync_platform_links'], scope: 'Editorial Pitching & Playlists', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Sparkles' },
  { number: 90, name: 'Video Music Agent', role: 'Coordinates music video releases and lyric video sync', category: 'Music / Artist', purpose: 'Coordinates music video premieres, YouTube Premiere links, and synced lyric videos.', tools: ['sync_video_audio', 'configure_premiere_time', 'link_track_to_video'], scope: 'Music Video Synchronization', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Film' },

  // 91-102: Record Label
  { number: 91, name: 'Label Manager Agent', role: 'Oversees record label roster and operations', category: 'Record Label', purpose: 'Oversees record label roster, artist applications, release quotas, and label policies.', tools: ['inspect_roster', 'set_label_capacity', 'audit_label_operations'], scope: 'Record Label Administration', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'ShieldCheck' },
  { number: 92, name: 'Artist Application Agent', role: 'Processes incoming artist join applications', category: 'Record Label', purpose: 'Processes incoming artist join applications, demos, social handles, and press kits.', tools: ['review_application', 'validate_applicant_links', 'score_application_fit'], scope: 'Artist Application Intake', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 93, name: 'Artist Approval Agent', role: 'Handles human-governed onboarding approvals', category: 'Record Label', purpose: 'Handles human-governed onboarding approvals, acceptance letters, and contract offers.', tools: ['grant_artist_approval', 'issue_acceptance_notice', 'reject_with_feedback'], scope: 'Application Approvals Gate', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'CheckCircle2' },
  { number: 94, name: 'Artist Portal Agent', role: 'Manages artist dashboard, submissions, and service requests', category: 'Record Label', purpose: 'Manages the signed artist portal: song submissions, service orders, and billing.', tools: ['manage_artist_session', 'render_portal_tabs', 'track_submission_progress'], scope: '/artist/* & Artist Portals', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Globe' },
  { number: 95, name: 'Artist Capacity Agent', role: 'Enforces maximum signed artist limits and bandwidth', category: 'Record Label', purpose: 'Enforces maximum roster capacity, available distribution slots, and engineer queues.', tools: ['check_capacity_limits', 'throttle_new_signings', 'report_slot_availability'], scope: 'Label Capacity Management', policy: 'CRITICAL_ONLY', icon: 'Sliders' },
  { number: 96, name: 'Label Distribution Agent', role: 'Coordinates distribution delivery for signed artists', category: 'Record Label', purpose: 'Coordinates distribution packages, ISRC generation, and delivery for signed artists.', tools: ['batch_deliver_tracks', 'verify_label_isrc_prefix', 'monitor_dsp_ingestion'], scope: 'Signed Artist Distribution', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Disc' },
  { number: 97, name: 'Label Pricing Agent', role: 'Configures joining fee (₹999), annual fee (₹1,999), and rates', category: 'Record Label', purpose: 'Configures label join plan (₹999 join + ₹1,999/yr), per-song distribution (₹3,000), VEVO, etc.', tools: ['update_pricing_plan', 'audit_pricing_history', 'validate_currency_inr'], scope: 'Label Pricing Engine & /admin/label/pricing', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'BarChart3' },
  { number: 98, name: 'Artist Agreement Agent', role: 'Manages official 12-clause legal agreements and digital signatures', category: 'Record Label', purpose: 'Manages official 12-clause artist contracts, 15% revenue share clauses, and digital sign-offs.', tools: ['generate_agreement_pdf', 'record_digital_signature', 'verify_hash_integrity'], scope: 'Legal Contracts & Digital Signatures', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 99, name: 'Label Payment Agent', role: 'Processes joining fees, renewals, and service checkouts', category: 'Record Label', purpose: 'Processes joining fees, annual renewals, and per-service checkouts securely.', tools: ['initiate_payment_order', 'verify_payment_status', 'record_payment_log'], scope: 'Payment Processing & Transactions', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Zap' },
  { number: 100, name: 'Label Invoice Agent', role: 'Generates itemized PDF invoices with unique INV numbers', category: 'Record Label', purpose: 'Generates itemized PDF invoices with unique IDs (e.g. INV-LBL-2026-XXXX), GST, and status.', tools: ['generate_invoice_record', 'calculate_tax_breakdown', 'render_invoice_print'], scope: 'Invoices & Financial Records', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 101, name: 'Label Communication Agent', role: 'Sends onboarding instructions, statements, and bulletins', category: 'Record Label', purpose: 'Sends official onboarding instructions, statements, and label bulletins to signed artists.', tools: ['send_label_bulletin', 'dispatch_welcome_packet', 'log_communication'], scope: 'Label Artist Communications', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 102, name: 'Label Support Agent', role: 'Provides dedicated VIP ticketing for signed roster artists', category: 'Record Label', purpose: 'Provides dedicated VIP ticketing, release troubleshooting, and distribution help.', tools: ['resolve_artist_ticket', 'escalate_distro_delay', 'log_support_interaction'], scope: 'VIP Artist Help Desk', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },

  // 103-110: Video / Media
  { number: 103, name: 'Video Agent', role: 'Manages official YouTube embeds, video player, and playlists', category: 'Video / Media', purpose: 'Manages official YouTube embeds, video player controls, and cinema video showcases.', tools: ['embed_youtube_video', 'sanitize_video_params', 'verify_video_availability'], scope: 'Video Showcase & Media Players', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Film' },
  { number: 104, name: 'Video Upload Agent', role: 'Handles video file intake, format checking, and quotas', category: 'Video / Media', purpose: 'Handles video file intake, format validation (MP4/ProRes), and size quota checks.', tools: ['validate_video_container', 'check_bitrate_resolution', 'enforce_upload_limit'], scope: 'Video Ingestion Pipelines', policy: 'CRITICAL_ONLY', icon: 'Camera' },
  { number: 105, name: 'Video Metadata Agent', role: 'Maintains video titles, descriptions, chapters, and tags', category: 'Video / Media', purpose: 'Maintains video titles, descriptions, timestamped chapters, and credit tags.', tools: ['format_video_chapters', 'sync_video_tags', 'optimize_video_title'], scope: 'Video Metadata & Chapters', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 106, name: 'Thumbnail Agent', role: 'Generates and audits 16:9 high-res video thumbnails', category: 'Video / Media', purpose: 'Generates and audits 16:9 1080p high-contrast video thumbnails with branding.', tools: ['validate_thumbnail_ratio', 'check_thumbnail_sharpness', 'generate_poster_frame'], scope: 'Video Posters & Thumbnails', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Camera' },
  { number: 107, name: 'Media Processing Agent', role: 'Compresses, resizes, and encodes images and audio', category: 'Video / Media', purpose: 'Compresses, resizes, and encodes images to WebP/AVIF and audio waveforms.', tools: ['convert_to_webp', 'generate_waveform_json', 'compress_asset'], scope: 'Asset Processing Pipeline', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Sliders' },
  { number: 108, name: 'Transcoding Agent', role: 'Oversees HLS, adaptive streaming, and audio bitrates', category: 'Video / Media', purpose: 'Oversees HLS, adaptive streaming bitrates (320kbps MP3 / AAC), and audio normalization.', tools: ['normalize_audio_lufs', 'verify_hls_manifest', 'test_adaptive_bitrate'], scope: 'Audio/Video Transcoding', policy: 'CRITICAL_ONLY', icon: 'Cpu' },
  { number: 109, name: 'Media Storage Agent', role: 'Organizes cloud folders, asset naming, and CDN cache', category: 'Video / Media', purpose: 'Organizes cloud folders, enforces sanitized asset naming, and handles asset caching.', tools: ['organize_folders', 'purge_asset_cache', 'check_orphan_files'], scope: 'Media Asset Storage Trees', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Database' },
  { number: 110, name: 'Gallery Agent', role: 'Curates photo gallery grids, lightbox previews, and EXIF', category: 'Video / Media', purpose: 'Curates photo gallery grids, lightbox previews, photographer credits, and captions.', tools: ['curate_gallery_order', 'extract_exif_metadata', 'optimize_lightbox_speed'], scope: 'Photo Gallery & Lightbox', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Camera' },

  // 111-120: User Support
  { number: 111, name: 'AI Support Agent', role: 'Provides automated 24/7 intelligent fan assistance', category: 'User Support', purpose: 'Provides automated 24/7 intelligent assistance for music, shows, and account queries.', tools: ['query_artist_knowledge', 'synthesize_support_answer', 'suggest_helpful_actions'], scope: '24/7 Fan AI Assistant', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Bot' },
  { number: 112, name: 'User Help Agent', role: 'Maintains platform help center guides and walk-throughs', category: 'User Support', purpose: 'Maintains platform help center articles, walk-through tutorials, and search indexes.', tools: ['update_help_article', 'search_faq_catalog', 'track_article_feedback'], scope: 'Help Center & Documentation', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 113, name: 'Support Ticket Agent', role: 'Manages support tickets, routing, priorities, and SLAs', category: 'User Support', purpose: 'Manages support tickets, assigns category priorities, and monitors resolution SLAs.', tools: ['create_support_ticket', 'update_ticket_status', 'assign_ticket_agent'], scope: 'Ticketing System & Queue', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Layers' },
  { number: 114, name: 'Account Support Agent', role: 'Assists fans with profile updates, 2FA, and password reset', category: 'User Support', purpose: 'Assists fans with profile updates, 2FA guidance, and email notification settings.', tools: ['assist_profile_update', 'verify_identity_challenge', 'reset_session_safely'], scope: 'Fan Account Support', policy: 'CRITICAL_ONLY', icon: 'Lock' },
  { number: 115, name: 'Booking Support Agent', role: 'Handles live show promoter inquiries and rider requests', category: 'User Support', purpose: 'Handles concert promoter inquiries, stage tech rider requests, and dates availability.', tools: ['process_booking_inquiry', 'send_tech_rider_pdf', 'log_promoter_contact'], scope: 'Promoter Inquiries & Booking Desk', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 116, name: 'Music Support Agent', role: 'Assists with audio playback, lyrics queries, and lossless audio', category: 'User Support', purpose: 'Assists fans experiencing playback issues, streaming buffering, or lyrics questions.', tools: ['diagnose_playback_issue', 'lookup_lyrics', 'verify_dsp_availability'], scope: 'Music Streaming Assistance', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Disc' },
  { number: 117, name: 'Distribution Support Agent', role: 'Resolves DSP ingestion inquiries and delivery delays', category: 'User Support', purpose: 'Resolves DSP ingestion delays, track take-down inquiries, and stores delivery.', tools: ['query_ingestion_status', 'check_dsp_store_links', 'open_distro_ticket'], scope: 'DSP & Distribution Support', policy: 'CRITICAL_ONLY', icon: 'Sliders' },
  { number: 118, name: 'Policy Assistant Agent', role: 'Answers fan questions regarding privacy, cookies, and terms', category: 'User Support', purpose: 'Answers fan questions regarding privacy, cookies, virtual coin rules, and refunds.', tools: ['explain_policy_clause', 'reiterate_non_cash_terms', 'provide_privacy_info'], scope: 'Policy Transparency & Guidance', policy: 'READ_ONLY_SUGGEST', icon: 'ShieldCheck' },
  { number: 119, name: 'FAQ Agent', role: 'Curates frequently asked questions with instant answers', category: 'User Support', purpose: 'Curates dynamic FAQ entries based on frequent search queries and fan tickets.', tools: ['aggregate_top_questions', 'update_faq_entry', 'measure_faq_helpfulness'], scope: 'FAQ Database & Dynamic Answers', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 120, name: 'Escalation Agent', role: 'Escalates urgent VIP or legal inquiries to human owner', category: 'User Support', purpose: 'Detects high-priority tickets, legal complaints, or urgent inquiries and notifies owner.', tools: ['trigger_owner_alert', 'flag_urgent_priority', 'lock_sensitive_thread'], scope: 'Executive Escalation Pipeline', policy: 'CRITICAL_ONLY', icon: 'AlertTriangle' },

  // 121-132: AI / Coins / Wallet
  { number: 121, name: 'PRANTIK AI Agent', role: 'Official AI intelligence for PRANTIK SARKAR ARTIST RECORD and portal users', category: 'AI / Coins / Wallet', purpose: 'Handles official label inquiries (inside label), user account records (RBAC), and general AI knowledge (outside label) with strict factual grounding.', tools: ['generate_persona_response', 'retrieve_authorized_label_data', 'disambiguate_intent', 'enforce_access_control'], scope: 'Official Label & Portal AI Engine', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Sparkles' },
  { number: 122, name: 'AI Usage Agent', role: 'Tracks real-time session duration and second-by-second burn', category: 'AI / Coins / Wallet', purpose: 'Tracks real-time session duration, countdown clocks, and second-by-second usage.', tools: ['track_active_seconds', 'deduct_balance_realtime', 'trigger_minute_warning'], scope: 'Realtime Usage Burn Engine', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Clock' },
  { number: 123, name: 'AI Session Agent', role: 'Maintains conversational state, tokens, and context window', category: 'AI / Coins / Wallet', purpose: 'Maintains conversational state, message history, and context limits safely.', tools: ['save_message_history', 'truncate_context', 'summarize_session'], scope: 'AI Chat Sessions & History', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Terminal' },
  { number: 124, name: 'AI Token/Usage Tracking Agent', role: 'Logs model tokens, API costs, and latency metrics', category: 'AI / Coins / Wallet', purpose: 'Logs exact input/output tokens, cost calculations, and inference response latencies.', tools: ['record_token_metric', 'calculate_inference_cost', 'enforce_token_budget'], scope: 'Token Telemetry & Cost Accounting', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'BarChart3' },
  { number: 125, name: 'Coin Wallet Agent', role: 'Governs fan virtual coin balances and 24h free allowances', category: 'AI / Coins / Wallet', purpose: 'Governs virtual coin balances, daily 60-second free AI allowances, and reset clocks.', tools: ['credit_wallet_coins', 'check_wallet_balance', 'grant_free_allowance'], scope: 'User Wallet & Non-Cash Ledger', policy: 'CRITICAL_ONLY', icon: 'Zap' },
  { number: 126, name: 'Coin Transaction Agent', role: 'Maintains immutable transaction ledger entries', category: 'AI / Coins / Wallet', purpose: 'Maintains immutable transaction ledger entries for all coin purchases, claims, and burns.', tools: ['record_ledger_entry', 'verify_ledger_balance', 'prevent_negative_balance'], scope: 'Immutable Coin Ledger', policy: 'CRITICAL_ONLY', icon: 'Database' },
  { number: 127, name: 'Payment Verification Agent', role: 'Verifies coin pack payment receipts with idempotent hashing', category: 'AI / Coins / Wallet', purpose: 'Verifies coin pack payment webhooks, prevents double credits, and audits order IDs.', tools: ['verify_receipt_signature', 'check_idempotency_key', 'confirm_order_funds'], scope: 'Payment Verification Gate', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Lock' },
  { number: 128, name: 'AI Billing Agent', role: 'Manages coin package pricing, promotional rates, and receipts', category: 'AI / Coins / Wallet', purpose: 'Manages coin package pricing (Starter, Pro, Ultra), discounts, and user receipts.', tools: ['list_coin_packages', 'apply_promo_code', 'issue_coin_receipt'], scope: 'Coin Packaging & Billing', policy: 'CRITICAL_ONLY', icon: 'BarChart3' },
  { number: 129, name: 'AI Review Agent', role: 'Conducts post-session quality and sentiment evaluations', category: 'AI / Coins / Wallet', purpose: 'Conducts post-session quality audits, thumbs up/down scoring, and answer fidelity checks.', tools: ['score_interaction_quality', 'detect_hallucinations', 'log_sentiment_score'], scope: 'AI Output Quality Audits', policy: 'READ_ONLY_SUGGEST', icon: 'CheckCircle2' },
  { number: 130, name: 'AI Abuse Detection Agent', role: 'Detects prompt injections, jailbreaks, and offensive inputs', category: 'AI / Coins / Wallet', purpose: 'Detects prompt injection attempts, toxic inputs, spam flooding, and jailbreaks.', tools: ['scan_for_injection', 'enforce_safety_boundary', 'terminate_abusive_session'], scope: 'AI Prompt Safety & Filtering', policy: 'CRITICAL_ONLY', icon: 'ShieldAlert' },
  { number: 131, name: 'AI Provider Agent', role: 'Manages API connectors to Google Gemini and fallback providers', category: 'AI / Coins / Wallet', purpose: 'Manages server-side connections to Gemini Flash, Pro, and fallback models.', tools: ['dispatch_model_call', 'handle_provider_outage', 'verify_api_connectivity'], scope: 'AI Model Connectors & API Gateways', policy: 'CRITICAL_ONLY', icon: 'Cpu' },
  { number: 132, name: 'AI Model Routing Agent', role: 'Routes queries to the fastest, most cost-effective model', category: 'AI / Coins / Wallet', purpose: 'Routes queries dynamically based on complexity, required context, and latency targets.', tools: ['evaluate_query_complexity', 'select_optimal_model', 'track_model_latency'], scope: 'Intelligent Model Routing', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Sliders' },

  // 133-139: Referral / Rewards
  { number: 133, name: 'Referral Agent', role: 'Manages fan referral links, invite tracking, and credits', category: 'Referral / Rewards', purpose: 'Generates unique referral codes for fans and tracks registrations and rewards.', tools: ['generate_referral_code', 'track_referral_click', 'attribute_conversion'], scope: 'Referral Engine & Attribution', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Gift' },
  { number: 134, name: 'Referral Qualification Agent', role: 'Verifies referee qualification criteria before granting rewards', category: 'Referral / Rewards', purpose: 'Verifies referee qualification criteria: account age, verified email, activity check.', tools: ['check_qualification_rules', 'approve_referral_reward', 'disqualify_referral'], scope: 'Reward Qualification Rules', policy: 'CRITICAL_ONLY', icon: 'CheckCircle2' },
  { number: 135, name: 'Referral Fraud Detection Agent', role: 'Detects self-referrals, multiple accounts, and IP farms', category: 'Referral / Rewards', purpose: 'Detects self-referrals, sybil attacks, temporary emails, and device fingerprint matching.', tools: ['detect_device_fingerprint', 'flag_ip_clustering', 'blacklist_fraudulent_code'], scope: 'Anti-Fraud & Sybil Defense', policy: 'CRITICAL_ONLY', icon: 'ShieldAlert' },
  { number: 136, name: 'Rewards Agent', role: 'Governs reward point catalog, claims, and virtual bonuses', category: 'Referral / Rewards', purpose: 'Governs promotional reward claims, free bonus minutes, and badge achievements.', tools: ['process_reward_claim', 'grant_bonus_minutes', 'list_claimable_rewards'], scope: 'Promotional Rewards Catalog', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Gift' },
  { number: 137, name: 'Daily Reward Agent', role: 'Manages daily check-in streaks and RNG luck rolls', category: 'Referral / Rewards', purpose: 'Manages daily check-in streaks, server-authoritative RNG luck rolls, and multipliers.', tools: ['execute_daily_checkin', 'roll_rng_wheel', 'calculate_streak_bonus'], scope: 'Daily Check-In & Luck Rolls', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Clock' },
  { number: 138, name: 'Redemption Agent', role: 'Processes reward redemptions into non-cash platform credits', category: 'Referral / Rewards', purpose: 'Processes non-cash credit redemptions, virtual badge claims, and exclusive content unlocks.', tools: ['redeem_reward_item', 'unlock_exclusive_track', 'audit_redemption_ledger'], scope: 'Redemption & Unlocks', policy: 'CRITICAL_ONLY', icon: 'CheckCircle2' },
  { number: 139, name: 'Campaign Agent', role: 'Configures limited-time seasonal promotional reward campaigns', category: 'Referral / Rewards', purpose: 'Configures limited-time promotional campaigns, album launch bonus drops, and contests.', tools: ['launch_campaign', 'set_campaign_window', 'track_campaign_roi'], scope: 'Promotional Reward Campaigns', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Sparkles' },

  // 140-145: Communication
  { number: 140, name: 'Email Agent', role: 'Manages transactional emails and newsletter dispatch', category: 'Communication', purpose: 'Manages transactional emails, booking confirmations, and newsletter releases.', tools: ['send_transactional_email', 'validate_email_syntax', 'track_email_delivery'], scope: 'Email Dispatch & Templates', policy: 'CRITICAL_ONLY', icon: 'FileText' },
  { number: 141, name: 'Notification Agent', role: 'Dispatches in-app notification alerts and announcements', category: 'Communication', purpose: 'Dispatches in-app notifications, release bells, badge alerts, and system notices.', tools: ['dispatch_in_app_notif', 'mark_notif_read', 'broadcast_system_alert'], scope: 'In-App Notification Stream', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity' },
  { number: 142, name: 'Push Notification Agent', role: 'Oversees Web Push subscriptions and release alerts', category: 'Communication', purpose: 'Oversees Web Push subscriptions, permission requests, and background release alerts.', tools: ['send_push_message', 'manage_push_subscription', 'verify_vapid_keys'], scope: 'Web Push & PWA Notifications', policy: 'CRITICAL_ONLY', icon: 'Flame' },
  { number: 143, name: 'Message Agent', role: 'Handles fan contact submissions and artist direct inbox', category: 'Communication', purpose: 'Handles fan contact submissions, feedback forms, and administrative inbox routing.', tools: ['route_inbox_message', 'archive_message', 'sanitize_contact_form'], scope: 'Direct Messages & Fan Inbox', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 144, name: 'Template Agent', role: 'Maintains responsive email templates and brand formatting', category: 'Communication', purpose: 'Maintains responsive HTML email templates with dark luxury branding.', tools: ['render_email_template', 'test_email_responsiveness', 'update_email_footer'], scope: 'Email & Message Templates', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Palette' },
  { number: 145, name: 'Communication Audit Agent', role: 'Maintains compliance records for anti-spam and opt-outs', category: 'Communication', purpose: 'Maintains compliance with CAN-SPAM, opt-out requests, and communication audit logs.', tools: ['enforce_unsubscribe', 'audit_sent_messages', 'verify_consent_records'], scope: 'Communication Compliance & Unsub', policy: 'CRITICAL_ONLY', icon: 'ShieldCheck' },

  // 146-154: Analytics
  { number: 146, name: 'Analytics Agent', role: 'Centralizes platform telemetry, metrics, and KPI reports', category: 'Analytics', purpose: 'Centralizes platform telemetry, KPI metrics, conversion funnels, and executive summaries.', tools: ['generate_kpi_summary', 'aggregate_metrics', 'export_analytics_csv'], scope: 'Platform Analytics Hub', policy: 'READ_ONLY_SUGGEST', icon: 'BarChart3' },
  { number: 147, name: 'Website Analytics Agent', role: 'Tracks pageviews, bounce rates, visit durations, and flows', category: 'Analytics', purpose: 'Tracks pageviews, bounce rates, user journey flows, and section engagement heatmaps.', tools: ['track_pageview', 'compute_bounce_rate', 'analyze_dropoff_points'], scope: 'Website Traffic Analytics', policy: 'READ_ONLY_SUGGEST', icon: 'Activity' },
  { number: 148, name: 'User Analytics Agent', role: 'Analyzes user cohorts, retention rates, and active fans', category: 'Analytics', purpose: 'Analyzes user cohorts, retention curves, daily active users, and signup trends.', tools: ['analyze_user_cohorts', 'calculate_retention_rate', 'segment_fan_base'], scope: 'Fan Demographics & Retention', policy: 'READ_ONLY_SUGGEST', icon: 'BarChart3' },
  { number: 149, name: 'Content Analytics Agent', role: 'Measures engagement across articles, videos, and photos', category: 'Analytics', purpose: 'Measures reading times, video play rates, photo views, and press link interactions.', tools: ['measure_read_time', 'compute_completion_rate', 'rank_top_content'], scope: 'Content Engagement Analytics', policy: 'READ_ONLY_SUGGEST', icon: 'FileText' },
  { number: 150, name: 'Music Analytics Agent', role: 'Analyzes track plays, skips, waveform drop-offs, and repeats', category: 'Analytics', purpose: 'Analyzes track plays, skip rates, repeat listens, and audio player seek behavior.', tools: ['track_stream_play', 'calculate_skip_rate', 'analyze_audio_dropoff'], scope: 'Music Stream Telemetry', policy: 'READ_ONLY_SUGGEST', icon: 'Disc' },
  { number: 151, name: 'Business Analytics Agent', role: 'Tracks gross bookings, coin sales, and label revenue', category: 'Analytics', purpose: 'Tracks gross booking volume, coin package revenues, and label services margins.', tools: ['calculate_gross_revenue', 'track_arpu', 'forecast_run_rate'], scope: 'Business & Financial Metrics', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'BarChart3' },
  { number: 152, name: 'Error Analytics Agent', role: 'Tracks mean-time-to-recovery and error frequency spikes', category: 'Analytics', purpose: 'Tracks client-side exceptions, HTTP 500 errors, MTTR, and degradation trends.', tools: ['compute_error_rate', 'detect_anomaly_spike', 'correlate_deploy_errors'], scope: 'Error Rates & Reliability Metrics', policy: 'READ_ONLY_SUGGEST', icon: 'AlertTriangle' },
  { number: 153, name: 'AI Analytics Agent', role: 'Measures AI model token efficiency, latency, and feedback', category: 'Analytics', purpose: 'Measures token efficiency, inference response latencies, and satisfaction ratings.', tools: ['compute_cost_per_query', 'chart_latency_percentiles', 'analyze_user_feedback'], scope: 'AI Performance & Economics', policy: 'READ_ONLY_SUGGEST', icon: 'Cpu' },
  { number: 154, name: 'Conversion Analytics Agent', role: 'Measures funnel conversions for onboarding and sales', category: 'Analytics', purpose: 'Measures multi-step conversion funnels for artist onboarding, ticketing, and coin packs.', tools: ['map_funnel_steps', 'compute_conversion_rate', 'identify_friction_points'], scope: 'Conversion Funnel Telemetry', policy: 'READ_ONLY_SUGGEST', icon: 'Flame' },

  // 155-165: Admin / Operations
  { number: 155, name: 'Admin Assistant Agent', role: 'Assists human platform administrator with daily chores', category: 'Admin / Operations', purpose: 'Assists platform administrators with quick actions, summaries, and routine checks.', tools: ['summarize_admin_tasks', 'execute_quick_action', 'draft_announcement'], scope: 'Admin Studio Operations', policy: 'CRITICAL_ONLY', icon: 'Bot' },
  { number: 156, name: 'User Management Agent', role: 'Manages user accounts, statuses, bans, and password resets', category: 'Admin / Operations', purpose: 'Manages user accounts, active/suspended status, role assignment, and verification.', tools: ['update_user_role', 'suspend_user_account', 'verify_user_email'], scope: 'User Records & Directory', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Lock' },
  { number: 157, name: 'Permission Management Agent', role: 'Audits and updates permission scopes and tool grants', category: 'Admin / Operations', purpose: 'Audits and updates administrator and agent permission scopes and tool permissions.', tools: ['grant_tool_permission', 'revoke_tool_permission', 'audit_permissions'], scope: 'Permissions Matrix & Grants', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'ShieldCheck' },
  { number: 158, name: 'Content Moderation Agent', role: 'Screens comments, fan submissions, and messages for spam', category: 'Admin / Operations', purpose: 'Screens comments, contact messages, and artist submissions for profanity and spam.', tools: ['scan_for_spam', 'flag_inappropriate_content', 'auto_moderate_text'], scope: 'Content Moderation Engine', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'ShieldAlert' },
  { number: 159, name: 'Activity Monitoring Agent', role: 'Tracks realtime administrative actions and user events', category: 'Admin / Operations', purpose: 'Tracks realtime administrative activities, changes, logins, and operational events.', tools: ['record_admin_event', 'stream_recent_activities', 'filter_activity_feed'], scope: 'Realtime Administrative Activity', policy: 'READ_ONLY_SUGGEST', icon: 'Activity' },
  { number: 160, name: 'Audit Log Agent', role: 'Guarantees audit log retention, search, and tamper evidence', category: 'Admin / Operations', purpose: 'Guarantees comprehensive audit log retention, search filters, and tamper evidence.', tools: ['query_audit_logs', 'export_audit_trail', 'verify_log_completeness'], scope: 'Master Audit Log Vault', policy: 'READ_ONLY_SUGGEST', icon: 'FileText' },
  { number: 161, name: 'System Health Agent', role: 'Evaluates entire portal subsystem availability and metrics', category: 'Admin / Operations', purpose: 'Evaluates all portal subsystems: database, AI, storage, player, and authentication.', tools: ['probe_subsystems', 'evaluate_system_score', 'generate_health_matrix'], scope: 'Full-System Health Arbitration', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },
  { number: 162, name: 'Settings Agent', role: 'Updates global website settings, maintenance, and branding', category: 'Admin / Operations', purpose: 'Updates artist name, tagline, maintenance mode toggle, and global contact metadata.', tools: ['update_site_settings', 'toggle_maintenance_mode', 'sync_site_metadata'], scope: 'Global Site Configuration', policy: 'CRITICAL_ONLY', icon: 'Sliders' },
  { number: 163, name: 'Configuration Agent', role: 'Manages dynamic feature flags and environment parameters', category: 'Admin / Operations', purpose: 'Manages dynamic feature flags, rollout percentages, and kill-switches.', tools: ['toggle_feature_flag', 'set_rollout_percentage', 'list_active_flags'], scope: 'Dynamic Feature Flags', policy: 'CRITICAL_ONLY', icon: 'Sliders' },
  { number: 164, name: 'Report Agent', role: 'Compiles periodic operational and business executive reports', category: 'Admin / Operations', purpose: 'Compiles periodic PDF/CSV operational reports, monthly summaries, and KPI digests.', tools: ['generate_monthly_digest', 'format_report_charts', 'schedule_report_export'], scope: 'Operational & Executive Reports', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'FileText' },
  { number: 165, name: 'Export/Import Agent', role: 'Handles full database exports, JSON backups, and seeds', category: 'Admin / Operations', purpose: 'Handles full database exports, JSON backup downloads, and validated JSON seeding.', tools: ['export_database_json', 'import_database_json', 'validate_import_schema'], scope: 'Database Export & Import Tools', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Database' },

  // 166-175: Legal / Policy
  { number: 166, name: 'Policy Agent', role: 'Oversees platform terms, disclosures, and legal documents', category: 'Legal / Policy', purpose: 'Oversees platform terms, legal disclosures, and policy document management.', tools: ['audit_policy_compliance', 'inspect_legal_copy', 'draft_policy_update'], scope: 'Platform Legal Documents', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 167, name: 'Terms Agent', role: 'Maintains Terms of Service, licensing, and usage contracts', category: 'Legal / Policy', purpose: 'Maintains the official Terms of Service, user commitments, and licensing policies.', tools: ['update_terms_of_service', 'record_terms_acceptance', 'verify_terms_version'], scope: 'Terms of Service Vault', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 168, name: 'Privacy Agent', role: 'Maintains Privacy Policy, telemetry disclaimers, and DPA', category: 'Legal / Policy', purpose: 'Maintains Privacy Policy, telemetry disclaimers, and data protection agreements.', tools: ['update_privacy_policy', 'audit_tracking_disclosures', 'format_dpa_agreement'], scope: 'Privacy Policy Document', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Lock' },
  { number: 169, name: 'Cookie Policy Agent', role: 'Maintains Cookie Policy and consent categorizations', category: 'Legal / Policy', purpose: 'Maintains Cookie Policy, banner texts, and tracking classifications (Strictly Necessary, Analytics).', tools: ['update_cookie_policy', 'classify_storage_keys', 'verify_opt_in_banner'], scope: 'Cookie Policy & Consent Banner', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 170, name: 'AI Policy Agent', role: 'Enforces AI usage guidelines, non-cash disclaimers, and ethics', category: 'Legal / Policy', purpose: 'Enforces AI usage guidelines, non-cash coin disclosures, and ethical boundaries.', tools: ['update_ai_policy', 'verify_non_cash_disclaimer', 'audit_ai_ethics'], scope: 'AI Governance & Ethics Policy', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Sparkles' },
  { number: 171, name: 'Refund Policy Agent', role: 'Maintains clear refund, chargeback, and dispute policies', category: 'Legal / Policy', purpose: 'Maintains clear refund, non-refundable coin pack disclaimers, and dispute terms.', tools: ['update_refund_policy', 'verify_dispute_terms', 'audit_refund_rules'], scope: 'Refund Policy Documentation', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 172, name: 'Booking Policy Agent', role: 'Maintains live show booking cancellation and rider policies', category: 'Legal / Policy', purpose: 'Maintains live concert cancellation terms, deposit requirements, and rider rules.', tools: ['update_booking_policy', 'format_cancellation_terms', 'verify_deposit_clauses'], scope: 'Concert & Booking Legal Terms', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 173, name: 'Distribution Policy Agent', role: 'Enforces takedown, rights ownership, and warranty rules', category: 'Legal / Policy', purpose: 'Enforces copyright ownership warranties, takedown clauses, and dispute procedures.', tools: ['enforce_takedown_policy', 'verify_originality_warranty', 'format_rights_clause'], scope: 'Music Distribution Legal Rules', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'ShieldCheck' },
  { number: 174, name: 'Community Rules Agent', role: 'Maintains fan conduct, comment guidelines, and anti-harassment', category: 'Legal / Policy', purpose: 'Maintains fan conduct guidelines, comment standards, and anti-harassment rules.', tools: ['update_community_rules', 'define_prohibited_conduct', 'publish_fan_code'], scope: 'Community Code of Conduct', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },
  { number: 175, name: 'Policy Versioning Agent', role: 'Preserves immutable change logs and versions of all policies', category: 'Legal / Policy', purpose: 'Preserves immutable version histories and timestamps for every policy revision.', tools: ['create_policy_version', 'diff_policy_revisions', 'list_policy_history'], scope: 'Policy Version History Archive', policy: 'READ_ONLY_SUGGEST', icon: 'History' },

  // 176-183: Data
  { number: 176, name: 'Data Validation Agent', role: 'Validates schema constraints, types, and input sanitization', category: 'Data', purpose: 'Validates data models against TypeScript schemas and sanitizes input vectors.', tools: ['validate_record_schema', 'sanitize_string_inputs', 'detect_malformed_json'], scope: 'Data Validation Pipeline', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'CheckCircle2' },
  { number: 177, name: 'Data Cleanup Agent', role: 'Purges expired sessions, temp cache, and orphan files', category: 'Data', purpose: 'Purges expired sessions, orphaned temporary uploads, and stale cache entries.', tools: ['purge_stale_sessions', 'prune_old_notifications', 'vacuum_local_storage'], scope: 'Data Sanitization & Garbage Collection', policy: 'CRITICAL_ONLY', cron: '0 2 * * *' },
  { number: 178, name: 'Data Integrity Agent', role: 'Audits referential integrity and foreign key relationships', category: 'Data', purpose: 'Audits referential integrity between orders, invoices, users, and tasks.', tools: ['verify_foreign_keys', 'detect_orphaned_records', 'repair_broken_refs'], scope: 'Referential Integrity Checks', policy: 'CRITICAL_ONLY', icon: 'Database' },
  { number: 179, name: 'Data Import Agent', role: 'Validates and ingests external music, video, and user batches', category: 'Data', purpose: 'Validates and ingests batch imports of music releases, videos, or user data.', tools: ['parse_csv_import', 'validate_batch_records', 'commit_import_transaction'], scope: 'Batch Data Ingestion', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Layers' },
  { number: 180, name: 'Data Export Agent', role: 'Exports sanitized data snapshots in JSON, CSV, and XML formats', category: 'Data', purpose: 'Generates secure, sanitized data exports in JSON, CSV, and XML formats.', tools: ['build_export_payload', 'filter_unauthorized_fields', 'compress_export_zip'], scope: 'Data Extraction & Exports', policy: 'CRITICAL_ONLY', icon: 'FileText' },
  { number: 181, name: 'Database Backup Agent', role: 'Schedules and validates cryptographic database backups', category: 'Data', purpose: 'Schedules and validates cryptographic database backups with zero downtime.', tools: ['trigger_scheduled_backup', 'checksum_backup_file', 'archive_to_cold_storage'], scope: 'Automated Database Backups', policy: 'CRITICAL_ONLY', cron: '0 3 * * *' },
  { number: 182, name: 'Data Recovery Agent', role: 'Restores collections from verified backup snapshots', category: 'Data', purpose: 'Restores collections from verified backup snapshots in emergency events.', tools: ['restore_collection_snapshot', 'verify_restored_records', 'log_recovery_event'], scope: 'Emergency Data Recovery', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'History' },
  { number: 183, name: 'Data Retention Agent', role: 'Enforces statutory data retention and archival timelines', category: 'Data', purpose: 'Enforces financial record retention (7 years) and ephemeral log expiration.', tools: ['enforce_retention_rules', 'archive_aged_transactions', 'log_retention_prune'], scope: 'Data Retention Schedules', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Clock' },

  // 184-193: Operations / Reliability
  { number: 184, name: 'Job Scheduler Agent', role: 'Orchestrates timed cron jobs and recurring background tasks', category: 'Operations / Reliability', purpose: 'Orchestrates timed cron jobs, recurring health monitors, and background tasks.', tools: ['schedule_recurring_task', 'unschedule_task', 'inspect_cron_schedule'], scope: 'System Cron & Scheduler Engine', policy: 'CRITICAL_ONLY', icon: 'Clock' },
  { number: 185, name: 'Queue Manager Agent', role: 'Manages FIFO/priority task queues, workers, and concurrency', category: 'Operations / Reliability', purpose: 'Manages FIFO/priority task queues, worker pools, and task prioritization.', tools: ['reorder_queue_priority', 'pause_queue', 'flush_queue'], scope: 'Queue Infrastructure', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Layers' },
  { number: 186, name: 'Worker Manager Agent', role: 'Scales worker threads and enforces execution bounds', category: 'Operations / Reliability', purpose: 'Scales virtual worker threads, handles timeouts, and enforces memory caps.', tools: ['spawn_worker', 'terminate_hung_worker', 'monitor_worker_thread'], scope: 'Virtual Worker Pools', policy: 'CRITICAL_ONLY', icon: 'Cpu' },
  { number: 187, name: 'Incident Agent', role: 'Declares, logs, and classifies operational incidents', category: 'Operations / Reliability', purpose: 'Declares, logs, and classifies operational incidents by severity (Sev 1 - Sev 4).', tools: ['declare_incident', 'classify_severity', 'assign_incident_commander'], scope: 'Incident Management & Triage', policy: 'CRITICAL_ONLY', icon: 'AlertTriangle' },
  { number: 188, name: 'Incident Response Agent', role: 'Executes automated containment and post-mortem runbooks', category: 'Operations / Reliability', purpose: 'Executes automated containment runbooks, logs timelines, and generates post-mortems.', tools: ['execute_containment_step', 'compile_post_mortem', 'track_action_items'], scope: 'Incident Containment & Post-Mortem', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'ShieldAlert' },
  { number: 189, name: 'Maintenance Agent', role: 'Manages maintenance windows, customer banners, and drainage', category: 'Operations / Reliability', purpose: 'Manages scheduled maintenance windows, customer advisory banners, and traffic drainage.', tools: ['schedule_maintenance_window', 'enable_maintenance_banner', 'drain_active_sessions'], scope: 'Maintenance Operations', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Wrench' },
  { number: 190, name: 'Resource Monitoring Agent', role: 'Tracks CPU, memory, event loop lag, and storage quotas', category: 'Operations / Reliability', purpose: 'Tracks CPU usage, heap allocation, event loop lag, and storage quotas.', tools: ['sample_heap_memory', 'measure_event_loop_lag', 'alert_high_utilization'], scope: 'System Resource Telemetry', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity', cron: '*/10 * * * *' },
  { number: 191, name: 'Capacity Agent', role: 'Forecasts scaling requirements and infrastructure headroom', category: 'Operations / Reliability', purpose: 'Forecasts scaling requirements, peak traffic buffers, and headroom metrics.', tools: ['forecast_traffic_peak', 'evaluate_headroom', 'recommend_scaling'], scope: 'Capacity Planning & Forecasting', policy: 'READ_ONLY_SUGGEST', icon: 'BarChart3' },
  { number: 192, name: 'Cost Monitoring Agent', role: 'Tracks infrastructure and API operational expenditure', category: 'Operations / Reliability', purpose: 'Tracks cloud infrastructure, API inference costs, and monthly spending vs budget.', tools: ['aggregate_operational_costs', 'check_budget_burn_rate', 'alert_spend_overrun'], scope: 'Operational Cost Accounting', policy: 'READ_ONLY_SUGGEST', icon: 'BarChart3' },
  { number: 193, name: 'Service Health Agent', role: 'Aggregates status across all external integrations and APIs', category: 'Operations / Reliability', purpose: 'Aggregates health and latency across external APIs, CDNs, and payment gateways.', tools: ['probe_external_service', 'record_service_status', 'flag_degraded_service'], scope: 'External Service Availability', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Activity' },

  // 194-210: Advanced Agents
  { number: 194, name: 'Experiment Agent', role: 'Oversees feature experiments and hypothesis tracking', category: 'Advanced Agents', purpose: 'Oversees feature experiments, user hypothesis validation, and sample cohorts.', tools: ['create_experiment', 'track_hypothesis_outcome', 'conclude_experiment'], scope: 'Experimentation Framework', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Sparkles' },
  { number: 195, name: 'A/B Testing Agent', role: 'Executes split-testing for landing pages and CTAs', category: 'Advanced Agents', purpose: 'Executes randomized split-testing for call-to-action buttons, hero copy, and layouts.', tools: ['split_traffic_variant', 'compute_statistical_significance', 'declare_winner'], scope: 'A/B Testing Engine', policy: 'CRITICAL_ONLY', icon: 'Sliders' },
  { number: 196, name: 'Recommendation Agent', role: 'Generates personalized music and video recommendations', category: 'Advanced Agents', purpose: 'Generates personalized music and video recommendations based on listening history.', tools: ['compute_similarity_score', 'generate_recommended_queue', 'refresh_recommendations'], scope: 'Recommendation Engine', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Disc' },
  { number: 197, name: 'Personalization Agent', role: 'Customizes fan dashboard spotlights and preferred vibes', category: 'Advanced Agents', purpose: 'Customizes fan dashboard spotlights, preferred sub-genres, and greeting states.', tools: ['adapt_dashboard_layout', 'read_fan_preferences', 'personalize_spotlight'], scope: 'User Experience Personalization', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Palette' },
  { number: 198, name: 'Search Optimization Agent', role: 'Tunes fuzzy search rankings and typo tolerance', category: 'Advanced Agents', purpose: 'Tunes fuzzy search algorithms, typo tolerance, and catalog relevancy scores.', tools: ['tune_search_weights', 'reindex_search_lexicon', 'test_search_precision'], scope: 'Search Relevancy & Ranking', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Search' },
  { number: 199, name: 'Knowledge Base Agent', role: 'Indexes verified facts about Prantik Sarkar into vector store', category: 'Advanced Agents', purpose: 'Indexes verified facts about Prantik Sarkar, releases, lyrics, and discography.', tools: ['index_artist_facts', 'update_vector_embeddings', 'query_semantic_knowledge'], scope: 'Semantic Knowledge Base', policy: 'CRITICAL_ONLY', icon: 'Terminal' },
  { number: 200, name: 'AI Evaluation Agent', role: 'Scores model output fidelity and adherence to prompt rules', category: 'Advanced Agents', purpose: 'Scores model output fidelity, adherence to prompt rules, and hallucination rates.', tools: ['evaluate_response_fidelity', 'benchmark_model_score', 'flag_hallucination'], scope: 'AI Evaluation Framework', policy: 'READ_ONLY_SUGGEST', icon: 'CheckCircle2' },
  { number: 201, name: 'AI Quality Agent', role: 'Conducts automated regression tests on system prompts', category: 'Advanced Agents', purpose: 'Conducts automated regression tests on system prompts, preventing prompt drift.', tools: ['run_prompt_regression', 'compare_completion_quality', 'score_prompt_drift'], scope: 'System Prompt Quality Suite', policy: 'CRITICAL_ONLY', icon: 'CheckCircle2' },
  { number: 202, name: 'AI Guardrail Agent', role: 'Enforces hard output boundaries and safety filters', category: 'Advanced Agents', purpose: 'Enforces hard output boundaries, refusal policies, and prevents jailbreak responses.', tools: ['enforce_output_filter', 'block_harmful_content', 'intercept_unauthorized_action'], scope: 'AI Guardrails & Hard Boundaries', policy: 'CRITICAL_ONLY', icon: 'ShieldAlert' },
  { number: 203, name: 'Prompt Management Agent', role: 'Maintains versioned prompt templates and parameters', category: 'Advanced Agents', purpose: 'Maintains versioned prompt templates, system instructions, and temperature tuning.', tools: ['version_prompt_template', 'tune_hyperparameters', 'rollback_prompt_version'], scope: 'Prompt Template Registry', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'FileText' },
  { number: 204, name: 'Model Evaluation Agent', role: 'Benchmarks latency, cost, and accuracy across LLMs', category: 'Advanced Agents', purpose: 'Benchmarks latency, cost, and accuracy across Gemini models and specialized agents.', tools: ['benchmark_models_matrix', 'compare_cost_accuracy', 'generate_model_scorecard'], scope: 'Model Benchmarking & Scorecards', policy: 'READ_ONLY_SUGGEST', icon: 'BarChart3' },
  { number: 205, name: 'Agent Performance Agent', role: 'Measures task completion velocity and failure rates per agent', category: 'Advanced Agents', purpose: 'Measures task completion velocity, MTTR, and failure rates per individual agent.', tools: ['measure_agent_velocity', 'profile_task_latency', 'identify_agent_bottlenecks'], scope: 'Agent Performance Telemetry', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Flame' },
  { number: 206, name: 'Agent Audit Agent', role: 'Audits agent tool executions against authorized scopes', category: 'Advanced Agents', purpose: 'Audits every agent tool execution against authorized scopes to prevent privilege creep.', tools: ['audit_agent_invocations', 'detect_privilege_creep', 'flag_unauthorized_tool_attempt'], scope: 'Agent Execution Audits', policy: 'CRITICAL_ONLY', icon: 'ShieldCheck' },
  { number: 207, name: 'Agent Permission Agent', role: 'Configures granular tool access and approval requirements', category: 'Advanced Agents', purpose: 'Configures granular tool access, execution bounds, and approval requirements per agent.', tools: ['set_agent_permissions', 'modify_approval_requirement', 'enforce_least_privilege'], scope: 'Agent Permissions & Authority', policy: 'ALWAYS_REQUIRE_APPROVAL', icon: 'Lock' },
  { number: 208, name: 'Agent Scheduler', role: 'Schedules agent dispatch intervals and task cadence', category: 'Advanced Agents', purpose: 'Schedules agent dispatch intervals, queue pacing, and background batch cadence.', tools: ['schedule_agent_dispatch', 'adjust_task_cadence', 'coordinate_agent_sync'], scope: 'Agent Schedule & Cadence Engine', policy: 'AUTO_PUBLISH_LOW_RISK', icon: 'Clock', cron: '*/15 * * * *' },
  { number: 209, name: 'Agent Recovery Agent', role: 'Restores crashed or deadlocked agents to clean idle state', category: 'Advanced Agents', purpose: 'Detects deadlocked, hung, or crashed agents, clears task queues, and restores them.', tools: ['detect_hung_agent', 'restart_agent_process', 'flush_deadlocked_tasks'], scope: 'Agent Fault Recovery & Self-Healing', policy: 'CRITICAL_ONLY', icon: 'History' },
  { number: 210, name: 'Agent Supervisor', role: 'Supreme supervisor governing multi-agent consensus and health', category: 'Advanced Agents', purpose: 'Supreme supervisor governing multi-agent consensus, arbitration, and health arbitration.', tools: ['arbitrate_agent_dispute', 'enforce_system_consensus', 'issue_emergency_shutdown'], scope: 'Supreme Multi-Agent Arbitration', policy: 'CRITICAL_ONLY', icon: 'Bot' },
];

function buildAgentId(name: string, number: number): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  return `agent_${number}_${slug}`;
}

export const ALL_210_AI_AGENTS: AiAgentMode[] = RAW_AGENT_SPECS.map((spec) => {
  const id = buildAgentId(spec.name, spec.number);
  return {
    id,
    agent_number: spec.number,
    name: spec.name,
    role_title: spec.role,
    category: spec.category,
    purpose: spec.purpose,
    description: `Specialized autonomous AI agent #${spec.number} responsible for: ${spec.purpose}`,
    is_enabled: true,
    is_paused: false,
    emergency_stopped: false,
    schedule_cron: spec.cron || '0 0 * * *',
    allowed_tools: spec.tools,
    allowed_data_sources: [
      'Verified Website DB',
      'Authorized Schema',
      'Local Storage State',
      'Read-Only Music Index',
    ],
    scope_restrictions: [
      'Zero secrets exposure',
      'No raw card or credential logging',
      'Strict RBAC compliance',
      'No destructive schema drop without explicit approval',
    ],
    permission_scope: spec.scope,
    current_status: 'IDLE',
    active_tasks_count: 0,
    completed_tasks_count: Math.floor(12 + (spec.number % 37)),
    failed_tasks_count: 0,
    tokens_used_today: Math.floor(1200 + ((spec.number * 43) % 18000)),
    daily_token_limit: 500000,
    budget_limit_usd: spec.budgetUsd || 50,
    cost_today_usd: Number((((spec.number * 43) % 18000) * 0.000002).toFixed(4)),
    max_runtime_seconds: 300,
    max_concurrency: 3,
    retry_limit: 3,
    approval_policy: spec.policy || 'CRITICAL_ONLY',
    current_task: null,
    task_queue: [],
    task_history: [
      {
        id: `th_${spec.number}_1`,
        title: `Initial initialization and validation audit for ${spec.name}`,
        status: 'SUCCESS',
        duration_seconds: 4.2,
        tokens: 850,
        completed_at: new Date(Date.now() - 1000 * 60 * (30 + (spec.number % 120))).toISOString(),
      },
    ],
    execution_logs: [
      {
        id: `log_${spec.number}_init`,
        timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
        level: 'SUCCESS',
        message: `Agent #${spec.number} (${spec.name}) successfully registered in system orchestrator. Status: IDLE.`,
      },
    ],
    errors_count: 0,
    error_logs: [],
    performance_metrics: {
      average_response_ms: Math.floor(180 + ((spec.number * 17) % 320)),
      success_rate_percent: 99.4,
      throughput_per_min: Math.floor(4 + (spec.number % 8)),
      uptime_percent: 99.98,
    },
    version_history: [
      {
        version: 'v2.6.0',
        released_at: '2026-03-24T10:00:00Z',
        changelog: 'Synchronized with 210-agent orchestration matrix and global control standards.',
        author: 'Prantik Sarkar AI Systems',
      },
    ],
    logs: [
      {
        id: `log_${spec.number}_1`,
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        level: 'INFO',
        message: `Agent initialized and verified. Ready for task dispatch.`,
      },
    ],
    icon_name: spec.icon || 'Bot',
    key_responsibilities: [
      `Execute domain-specific tasks for ${spec.category}`,
      spec.purpose,
      `Comply with strict zero-leak secrets boundary`,
      `Report execution telemetry to Master AI and Supervisor`,
    ],
    workflow_steps: CONTROLLED_WORKFLOW_STEPS,
  };
});
