import { ChatConversation, ChatMessage } from '../types';

export const DEFAULT_CHAT_CONVERSATIONS: ChatConversation[] = [
  {
    id: 'conv_team_official',
    type: 'TEAM',
    title: 'PRANTIK SARKAR ARTIST RECORD — Executive Operations',
    description: 'Official internal communication channel for label management, executive producers, and platform administrators.',
    created_by: 'user_owner_01',
    mode: 'HUMAN_ACTIVE',
    ai_enabled: false,
    human_operator_id: 'user_owner_01',
    human_operator_name: 'Prantik Sarkar',
    human_operator_role: 'CREATOR',
    target_queue: 'ADMIN',
    human_response_timeout_seconds: 120,
    participants: [
      {
        user_id: 'user_owner_01',
        user_name: 'Prantik Sarkar',
        user_role: 'OWNER',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
        is_group_admin: true,
      },
      {
        user_id: 'user_admin_01',
        user_name: 'Management Operations',
        user_role: 'SUPER_ADMIN',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
        is_group_admin: true,
      },
      {
        user_id: 'user_editor_01',
        user_name: 'Press & Editorial Unit',
        user_role: 'EDITOR',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 25).toISOString(),
        is_group_admin: false,
      },
    ],
    participant_ids: ['user_owner_01', 'user_admin_01', 'user_editor_01'],
    topic: 'GENERAL',
    status: 'ACTIVE',
    user_states: {
      user_owner_01: { is_pinned: true, is_archived: false, is_muted: false, unread_count: 0 },
      user_admin_01: { is_pinned: true, is_archived: false, is_muted: false, unread_count: 0 },
      user_editor_01: { is_pinned: false, is_archived: false, is_muted: false, unread_count: 0 },
    },
    last_message: {
      id: 'msg_team_02',
      sender_id: 'user_admin_01',
      sender_name: 'Management Operations',
      text: 'All label distribution pipelines and ISRC tracking integrations are synchronized. Real-time updates active.',
      status: 'read',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'conv_label_support_channel',
    type: 'LABEL_SUPPORT',
    title: 'Label Roster & Artist Distribution Hotline',
    description: 'Direct communication desk for artist onboarding, release ingestion, DSP deliveries, and contract management.',
    created_by: 'user_owner_01',
    mode: 'HUMAN_ACTIVE',
    ai_enabled: false,
    human_operator_id: 'user_admin_01',
    human_operator_name: 'Management Operations',
    human_operator_role: 'ADMIN',
    target_queue: 'SUPPORT',
    human_response_timeout_seconds: 120,
    participants: [
      {
        user_id: 'user_owner_01',
        user_name: 'Prantik Sarkar',
        user_role: 'OWNER',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
        is_group_admin: true,
      },
      {
        user_id: 'user_admin_01',
        user_name: 'Management Operations',
        user_role: 'SUPER_ADMIN',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
        is_group_admin: true,
      },
    ],
    participant_ids: ['user_owner_01', 'user_admin_01'],
    topic: 'DISTRIBUTION',
    status: 'ACTIVE',
    user_states: {
      user_owner_01: { is_pinned: false, is_archived: false, is_muted: false, unread_count: 0 },
      user_admin_01: { is_pinned: false, is_archived: false, is_muted: false, unread_count: 0 },
    },
    last_message: {
      id: 'msg_label_01',
      sender_id: 'user_owner_01',
      sender_name: 'Prantik Sarkar',
      text: 'Welcome to PRANTIK SARKAR ARTIST RECORD direct label line. All releases, ISRC inquiries, and distribution reports are logged here.',
      status: 'delivered',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'conv_press_hotline',
    type: 'USER_SUPPORT',
    title: 'Press & Media Editorial Desk',
    description: 'Direct inquiries from journalists, interview inquiries, and EPK licensing inquiries.',
    created_by: 'user_editor_01',
    mode: 'WAITING_FOR_HUMAN',
    ai_enabled: true,
    target_queue: 'PRESS',
    human_response_timeout_seconds: 120,
    human_response_deadline: new Date(Date.now() + 120 * 1000).toISOString(),
    participants: [
      {
        user_id: 'user_editor_01',
        user_name: 'Press & Editorial Unit',
        user_role: 'EDITOR',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
        is_group_admin: true,
      },
      {
        user_id: 'user_owner_01',
        user_name: 'Prantik Sarkar',
        user_role: 'OWNER',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
        is_group_admin: true,
      },
    ],
    participant_ids: ['user_editor_01', 'user_owner_01'],
    topic: 'SUPPORT',
    status: 'ACTIVE',
    user_states: {
      user_editor_01: { is_pinned: false, is_archived: false, is_muted: false, unread_count: 0 },
      user_owner_01: { is_pinned: false, is_archived: false, is_muted: false, unread_count: 0 },
    },
    last_message: {
      id: 'msg_press_01',
      sender_id: 'user_editor_01',
      sender_name: 'Press & Editorial Unit',
      text: 'Press desk active. Verification window is open for incoming editorial requests.',
      status: 'read',
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'conv_user_support_channel',
    type: 'USER_SUPPORT',
    title: 'PRANTIK Platform Support & Fan Desk',
    description: 'General platform inquiries, account access, ticket escalation, and VIP member assistance.',
    created_by: 'user_admin_01',
    mode: 'WAITING_FOR_HUMAN',
    ai_enabled: true,
    target_queue: 'SUPPORT',
    human_response_timeout_seconds: 120,
    human_response_deadline: new Date(Date.now() + 120 * 1000).toISOString(),
    participants: [
      {
        user_id: 'user_admin_01',
        user_name: 'Management Operations',
        user_role: 'SUPER_ADMIN',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
        is_group_admin: true,
      },
      {
        user_id: 'user_owner_01',
        user_name: 'Prantik Sarkar',
        user_role: 'OWNER',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
        is_group_admin: true,
      },
    ],
    participant_ids: ['user_admin_01', 'user_owner_01'],
    topic: 'SUPPORT',
    status: 'ACTIVE',
    user_states: {
      user_admin_01: { is_pinned: false, is_archived: false, is_muted: false, unread_count: 0 },
      user_owner_01: { is_pinned: false, is_archived: false, is_muted: false, unread_count: 0 },
    },
    last_message: {
      id: 'msg_support_01',
      sender_id: 'user_admin_01',
      sender_name: 'Management Operations',
      text: 'Platform Support desk is online. Inquiries are handled with 2-minute human priority.',
      status: 'read',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'conv_ai_engine',
    type: 'AI',
    title: 'PRANTIK AI • Autonomous Label & Knowledge Engine',
    description: 'Official autonomous intelligence assistant for PRANTIK SARKAR ARTIST RECORD. Answers label operations, discography, release status, plus general knowledge.',
    created_by: 'user_owner_01',
    mode: 'AI_ACTIVE',
    ai_enabled: true,
    target_queue: 'ALL',
    participants: [
      {
        user_id: 'user_owner_01',
        user_name: 'Prantik Sarkar',
        user_role: 'OWNER',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
        is_group_admin: true,
      },
      {
        user_id: 'prantik_ai_bot',
        user_name: 'PRANTIK AI',
        user_role: 'AI',
        joined_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
        is_group_admin: false,
      },
    ],
    participant_ids: ['user_owner_01', 'prantik_ai_bot'],
    topic: 'GENERAL',
    status: 'ACTIVE',
    user_states: {
      user_owner_01: { is_pinned: true, is_archived: false, is_muted: false, unread_count: 0 },
    },
    last_message: {
      id: 'msg_ai_01',
      sender_id: 'prantik_ai_bot',
      sender_name: 'PRANTIK AI',
      text: 'Greetings! I am PRANTIK AI, the autonomous intelligence for PRANTIK SARKAR ARTIST RECORD. I can answer inquiries regarding verified label data, discography, release metadata, ISRC codes, Ditto distribution status, services, and payments, as well as general knowledge questions. How may I assist you today?',
      status: 'read',
      created_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    },
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
];

export const DEFAULT_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_team_01',
    conversation_id: 'conv_team_official',
    sender_id: 'user_owner_01',
    sender_name: 'Prantik Sarkar',
    sender_type: 'CREATOR',
    sender_role: 'OWNER',
    human_generated: true,
    ai_generated: false,
    text: 'Welcome to the PRANTIK CHAT internal communications grid. This channel is dedicated to label operations, roster planning, and platform oversight.',
    reactions: [
      { emoji: '🔥', user_id: 'user_admin_01', user_name: 'Management Operations', created_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString() },
      { emoji: '🎵', user_id: 'user_editor_01', user_name: 'Press & Editorial Unit', created_at: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString() },
    ],
    status: 'read',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 'msg_team_02',
    conversation_id: 'conv_team_official',
    sender_id: 'user_admin_01',
    sender_name: 'Management Operations',
    sender_type: 'ADMIN',
    sender_role: 'SUPER_ADMIN',
    human_generated: true,
    ai_generated: false,
    text: 'All label distribution pipelines and ISRC tracking integrations are synchronized. Real-time updates active.',
    reply_to_message_id: 'msg_team_01',
    reply_snippet: {
      id: 'msg_team_01',
      sender_name: 'Prantik Sarkar',
      text: 'Welcome to the PRANTIK CHAT internal communications grid...',
    },
    reactions: [
      { emoji: '👍', user_id: 'user_owner_01', user_name: 'Prantik Sarkar', created_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString() },
    ],
    status: 'read',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'msg_label_01',
    conversation_id: 'conv_label_support_channel',
    sender_id: 'user_owner_01',
    sender_name: 'Prantik Sarkar',
    sender_type: 'CREATOR',
    sender_role: 'OWNER',
    human_generated: true,
    ai_generated: false,
    text: 'Welcome to PRANTIK SARKAR ARTIST RECORD direct label line. All releases, ISRC inquiries, and distribution reports are logged here.',
    reactions: [],
    status: 'delivered',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
  {
    id: 'msg_support_01',
    conversation_id: 'conv_user_support_channel',
    sender_id: 'user_admin_01',
    sender_name: 'Management Operations',
    sender_type: 'SUPPORT',
    sender_role: 'SUPER_ADMIN',
    human_generated: true,
    ai_generated: false,
    text: 'Platform Support desk is online. Inquiries are handled with 2-minute human priority.',
    reactions: [],
    status: 'read',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'msg_press_01',
    conversation_id: 'conv_press_hotline',
    sender_id: 'user_editor_01',
    sender_name: 'Press & Editorial Unit',
    sender_type: 'PRESS',
    sender_role: 'EDITOR',
    human_generated: true,
    ai_generated: false,
    text: 'Press desk active. Verification window is open for incoming editorial requests.',
    reactions: [],
    status: 'read',
    created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: 'msg_ai_01',
    conversation_id: 'conv_ai_engine',
    sender_id: 'prantik_ai_bot',
    sender_name: 'PRANTIK AI',
    sender_type: 'AI',
    sender_role: 'AI',
    human_generated: false,
    ai_generated: true,
    text: 'Greetings! I am PRANTIK AI, the autonomous intelligence for PRANTIK SARKAR ARTIST RECORD. I can answer inquiries regarding verified label data, discography, release metadata, ISRC codes, Ditto distribution status, services, and payments, as well as general knowledge questions. How may I assist you today?',
    reactions: [
      { emoji: '🚀', user_id: 'user_owner_01', user_name: 'Prantik Sarkar', created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
    ],
    status: 'read',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
];
