import { MusicPlatform, ContactDepartment, PlatformCategory, PlatformRegion } from '../types';

export const DEFAULT_CONTACT_DEPARTMENTS: ContactDepartment[] = [
  {
    id: 'dept_booking',
    department_key: 'booking_licensing',
    title: 'Booking & Licensing',
    email: 'prantiksarkarartist@hotmail.com',
    description: 'Live performance bookings, festivals, concert headline appearances, master synchronization and commercial licensing.',
    display_order: 1,
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'dept_collab',
    department_key: 'collaborations',
    title: 'Collaborations',
    email: 'prantiksarkarartist@outlook.in',
    description: 'Artist collaborations, featured verses, vocal recordings, production partnerships, and songwriting inquiries.',
    display_order: 2,
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'dept_sponsor',
    department_key: 'sponsorships',
    title: 'Sponsorships',
    email: 'prantiksarkarartist@outlook.com',
    description: 'Brand endorsements, corporate partnerships, commercial endorsements, event sponsorships, and brand integrations.',
    display_order: 3,
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'dept_promo',
    department_key: 'promotion',
    title: 'Promotion',
    email: 'prantiksarkarartist@hotmail.com',
    description: 'Media publicity, radio pluggers, playlist pitching, interview requests, and press coverage opportunities.',
    display_order: 4,
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'dept_copyright',
    department_key: 'copyright_reports',
    title: 'Copyright / Re-upload Reports',
    email: 'prantiksarkar825@gmail.com',
    description: 'Official copyright administration, unauthorized re-upload infringement reports, DMCA notices, and content claims.',
    display_order: 5,
    is_active: true,
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date('2026-01-01').toISOString(),
  },
];

// Helper to construct platforms
const p = (
  id: string,
  platform_name: string,
  category: PlatformCategory,
  region: PlatformRegion,
  artist_profile_url: string,
  description: string,
  display_order: number,
  is_verified: boolean,
  is_active: boolean
): MusicPlatform => ({
  id,
  platform_name,
  category,
  region,
  artist_name: 'Prantik Sarkar',
  artist_profile_url,
  description,
  display_order,
  is_verified,
  is_active,
  created_at: new Date('2026-01-01').toISOString(),
  updated_at: new Date('2026-01-01').toISOString(),
});

export const DEFAULT_MUSIC_PLATFORMS: MusicPlatform[] = [
  // --- Major streaming ---
  p('plat_spotify', 'Spotify', 'Major streaming', 'Global', 'https://open.spotify.com/artist/prantiksarkar', 'Official verified Spotify artist profile with complete discography and editorial playlist features.', 1, true, true),
  p('plat_apple_music', 'Apple Music', 'Major streaming', 'Global', 'https://music.apple.com/artist/prantik-sarkar', 'Apple Music official artist page with lossless spatial audio streaming and albums.', 2, true, true),
  p('plat_youtube_music', 'YouTube Music', 'Major streaming', 'Global', 'https://music.youtube.com/channel/prantiksarkar', 'YouTube Music official artist channel featuring singles, official music videos, and live versions.', 3, true, true),
  p('plat_amazon_music', 'Amazon Music', 'Major streaming', 'Global', 'https://music.amazon.com/artists/prantik-sarkar', 'Amazon Music Unlimited and Prime Music artist catalog streaming worldwide.', 4, true, true),
  p('plat_deezer', 'Deezer', 'Major streaming', 'Global', 'https://www.deezer.com/artist/prantiksarkar', 'High-fidelity audio streaming available across Deezer global mobile and web apps.', 5, true, true),
  p('plat_tidal', 'TIDAL', 'Major streaming', 'Global', 'https://tidal.com/artist/prantik-sarkar', 'HiRes FLAC and Master Quality Authenticated streaming on TIDAL.', 6, true, true),
  p('plat_pandora', 'Pandora', 'Major streaming', 'North America', '', 'Custom radio algorithms and automated music stream stations on Pandora.', 7, false, false),
  p('plat_soundcloud', 'SoundCloud', 'Major streaming', 'Global', 'https://soundcloud.com/prantiksarkar', 'Official SoundCloud profile featuring exclusive previews, remixes, and originals.', 8, true, true),
  p('plat_audiomack', 'Audiomack', 'Major streaming', 'Global', 'https://audiomack.com/prantiksarkar', 'Audiomack streaming and offline downloads for hip hop and electronic sounds.', 9, true, true),
  p('plat_qobuz', 'Qobuz', 'Major streaming', 'Europe', '', 'Studio master 24-bit high-resolution audio streaming and download store.', 10, false, false),
  p('plat_napster', 'Napster', 'Major streaming', 'Global', '', 'Global on-demand streaming across mobile, desktop, and automotive sound systems.', 11, false, false),
  p('plat_iheartradio', 'iHeartRadio', 'Major streaming', 'North America', '', 'Digital broadcast radio stations, artist channels, and live podcasts.', 12, false, false),
  p('plat_anghami', 'Anghami', 'Major streaming', 'Asia', '', 'The leading music streaming platform in the Middle East and North Africa.', 13, false, false),

  // --- India / South Asia ---
  p('plat_jiosaavn', 'JioSaavn', 'India / South Asia', 'India / South Asia', 'https://www.jiosaavn.com/artist/prantik-sarkar', 'Official JioSaavn artist catalog with pan-India distribution and high-bitrate streaming.', 14, true, true),
  p('plat_gaana', 'Gaana', 'India / South Asia', 'India / South Asia', 'https://gaana.com/artist/prantik-sarkar', 'Official Gaana verified artist profile across Hindi, Bengali, and English discography.', 15, true, true),
  p('plat_hungama', 'Hungama Music', 'India / South Asia', 'India / South Asia', 'https://www.hungama.com/artist/prantik-sarkar', 'Hungama Music mobile app and web streaming portal across South Asia.', 16, true, true),
  p('plat_wynk', 'Wynk Music', 'India / South Asia', 'India / South Asia', 'https://wynk.in/u/prantiksarkar', 'Airtel Wynk Music official artist destination and HelloTunes integration.', 17, true, true),
  p('plat_resso', 'Resso', 'India / South Asia', 'India / South Asia', '', 'Social music streaming platform featuring interactive lyric sync.', 18, false, false),
  p('plat_moj', 'Moj', 'India / South Asia', 'India / South Asia', '', 'Short-form social audio distribution and verified sound catalog across India.', 19, false, false),
  p('plat_josh', 'Josh', 'India / South Asia', 'India / South Asia', '', 'Short-form audio synchronization and creator sound library on Josh.', 20, false, false),
  p('plat_raaga', 'Raaga', 'India / South Asia', 'India / South Asia', '', 'Regional and national Indian music catalog destination.', 21, false, false),
  p('plat_distrokid_india', 'DistroKid India destinations', 'India / South Asia', 'India / South Asia', '', 'Sub-continent aggregated direct streaming channels and ringtone networks.', 22, false, false),
  p('plat_hungama_aloud', 'Hungama Artist Aloud', 'India / South Asia', 'India / South Asia', '', 'Independent artist showcase and digital rights distribution channel.', 23, false, false),
  p('plat_saregama', 'Saregama Digital', 'India / South Asia', 'India / South Asia', '', 'Classic and contemporary subcontinental distribution networks.', 24, false, false),
  p('plat_tips', 'Tips Music Hub', 'India / South Asia', 'India / South Asia', '', 'Subcontinental streaming syndication network.', 25, false, false),
  p('plat_zee', 'Zee Music Digital', 'India / South Asia', 'India / South Asia', '', 'Digital music streaming channels and partner syndication.', 26, false, false),

  // --- Asia ---
  p('plat_kkbox', 'KKBOX', 'Asia', 'Asia', 'https://www.kkbox.com/artist/prantiksarkar', 'Leading digital music service across Taiwan, Hong Kong, Japan, Singapore, and Malaysia.', 27, true, true),
  p('plat_line_music', 'LINE MUSIC', 'Asia', 'Asia', '', 'Integrated music streaming on Japan and Thailand LINE messaging network.', 28, false, false),
  p('plat_melon', 'Melon', 'Asia', 'Asia', '', 'South Korea premier digital music subscription and chart service by Kakao.', 29, false, false),
  p('plat_genie', 'Genie Music', 'Asia', 'Asia', '', 'Major South Korean music service with lossless FLAC playback.', 30, false, false),
  p('plat_flo', 'FLO', 'Asia', 'Asia', '', 'AI-driven music streaming service by SK Telecom in South Korea.', 31, false, false),
  p('plat_bugs', 'Bugs!', 'Asia', 'Asia', '', 'Pioneer Korean digital audio streaming and lossless download portal by NHN.', 32, false, false),
  p('plat_vibe', 'VIBE', 'Asia', 'Asia', '', 'Naver cutting-edge AI music service in South Korea.', 33, false, false),
  p('plat_awa', 'AWA', 'Asia', 'Asia', '', 'Popular Japanese subscription music streaming service by CyberAgent & Avex.', 34, false, false),
  p('plat_rakuten', 'Rakuten Music', 'Asia', 'Asia', '', 'Japanese digital music service linked to Rakuten ecosystem.', 35, false, false),
  p('plat_mora', 'mora', 'Asia', 'Asia', '', 'Sony Music Solutions high-resolution audio store in Japan.', 36, false, false),
  p('plat_recochoku', 'RecoChoku', 'Asia', 'Asia', '', 'Japanese digital ringtone and music download service.', 37, false, false),
  p('plat_tencent', 'Tencent Music', 'Asia', 'Asia', '', 'Tencent Music Entertainment ecosystem powering 800M+ listeners.', 38, false, false),
  p('plat_qq_music', 'QQ Music', 'Asia', 'Asia', '', 'Leading music streaming platform in China with verified artist credentials.', 39, false, false),
  p('plat_kugou', 'Kugou', 'Asia', 'Asia', '', 'Massive streaming service with lyric-karaoke engine across China.', 40, false, false),
  p('plat_kuwo', 'Kuwo', 'Asia', 'Asia', '', 'Dedicated high-fidelity music and audiobook hub across China.', 41, false, false),
  p('plat_netease', 'NetEase Cloud Music', 'Asia', 'Asia', '', 'China community-driven indie and electronic music streaming platform.', 42, false, false),
  p('plat_joox_asia', 'JOOX Asia', 'Asia', 'Asia', '', 'Free and VIP music streaming in Hong Kong, Indonesia, Malaysia, and Thailand.', 43, false, false),
  p('plat_bilibili', 'Bilibili Music', 'Asia', 'Asia', '', 'Youth creator music and video hub with audio streams.', 44, false, false),

  // --- Africa ---
  p('plat_boomplay', 'Boomplay', 'Africa', 'Africa', 'https://www.boomplay.com/artists/prantiksarkar', 'Africa largest music streaming and download service with 100M+ active users.', 45, true, true),
  p('plat_audiomack_africa', 'Audiomack Africa', 'Africa', 'Africa', '', 'Dedicated regional African curation for Afrobeats, Amapiano, and hip hop.', 46, false, false),
  p('plat_mdundo', 'Mdundo', 'Africa', 'Africa', '', 'Pan-African music distribution platform with low-bandwidth mobile optimization.', 47, false, false),
  p('plat_music_in_africa', 'Music In Africa platforms', 'Africa', 'Africa', '', 'Information and music portal for the African music sector.', 48, false, false),
  p('plat_joox_africa', 'JOOX Africa', 'Africa', 'Africa', '', 'Music streaming service operating in South Africa.', 49, false, false),
  p('plat_simfy_africa', 'Simfy Africa', 'Africa', 'Africa', '', 'Pioneering streaming platform in South Africa and East Africa.', 50, false, false),
  p('plat_udux', 'UduX', 'Africa', 'Africa', '', 'Nigeria-based subscription music streaming and video experience.', 51, false, false),
  p('plat_playafrika', 'PlayAfrika', 'Africa', 'Africa', '', 'African digital content and indie streaming channel.', 52, false, false),

  // --- Latin America ---
  p('plat_claro_musica', 'Claro Música', 'Latin America', 'Latin America', '', 'Leading music service in 16 Latin American countries by América Móvil.', 53, false, false),
  p('plat_deezer_latam', 'Deezer LATAM', 'Latin America', 'Latin America', '', 'Regional Deezer editorial playlists and verified artist integration across LATAM.', 54, false, false),
  p('plat_youtube_latam', 'YouTube Music LATAM', 'Latin America', 'Latin America', '', 'Regional YouTube Music channel distribution across Latin America.', 55, false, false),
  p('plat_spotify_latam', 'Spotify LATAM', 'Latin America', 'Latin America', '', 'Top Latin American playlists, daily mix charts, and regional hubs.', 56, false, false),
  p('plat_tidal_latam', 'Tidal LATAM', 'Latin America', 'Latin America', '', 'Hi-Fi streaming destination across Brazil, Mexico, and South America.', 57, false, false),
  p('plat_apple_latam', 'Apple Music LATAM', 'Latin America', 'Latin America', '', 'Latin American Apple Music radio stations and regional curations.', 58, false, false),
  p('plat_trebel', 'Trebel Music', 'Latin America', 'Latin America', '', 'Licensed music app for free offline listening with media rewards.', 59, false, false),
  p('plat_palcomp3', 'Palco MP3', 'Latin America', 'Latin America', '', 'Brazil largest independent music hub for emerging artists.', 60, false, false),

  // --- Europe ---
  p('plat_qobuz_eu', 'Qobuz Europe', 'Europe', 'Europe', '', 'French high-resolution streaming platform and digital download boutique.', 61, false, false),
  p('plat_napster_eu', 'Napster Europe', 'Europe', 'Europe', '', 'European digital catalog streaming across 30+ European nations.', 62, false, false),
  p('plat_tidal_eu', 'TIDAL Europe', 'Europe', 'Europe', '', 'High-fidelity lossless streaming across UK, Germany, France, and Nordic nations.', 63, false, false),
  p('plat_musicme', 'MusicMe', 'Europe', 'Europe', '', 'French on-demand music streaming and library portal.', 64, false, false),
  p('plat_7digital', '7digital', 'Europe', 'Europe', '', 'Leading B2B music technology company and digital download store.', 65, false, false),
  p('plat_yandex', 'Yandex Music', 'Europe', 'Europe', '', 'Prominent streaming platform in Eastern Europe with personalized smart playlists.', 66, false, false),
  p('plat_zvuk', 'Zvuk HiFi', 'Europe', 'Europe', '', 'High-fidelity audio streaming service with millions of lossless tracks.', 67, false, false),

  // --- Classical / specialist ---
  p('plat_idagio', 'IDAGIO', 'Classical / specialist', 'Global', '', 'The leading streaming service dedicated exclusively to classical and orchestral audio.', 68, false, false),
  p('plat_presto', 'Presto Music', 'Classical / specialist', 'Europe', '', 'UK specialist classical and jazz online retailer and high-res streaming service.', 69, false, false),
  p('plat_primephonic', 'Primephonic destinations', 'Classical / specialist', 'Global', '', 'Comprehensive classical search and metadata ecosystem.', 70, false, false),
  p('plat_classical_archives', 'Classical Archives', 'Classical / specialist', 'North America', '', 'The ultimate classical music site with indexed composers, movements, and performers.', 71, false, false),
  p('plat_naxos', 'Naxos Music Library', 'Classical / specialist', 'Global', '', 'The most comprehensive classical music digital streaming library for education and pros.', 72, false, false),
  p('plat_medici', 'Medici.tv', 'Classical / specialist', 'Europe', '', 'Leading classical music video streaming channel and audio library.', 73, false, false),
  p('plat_gramophone', 'Gramophone Sound', 'Classical / specialist', 'Europe', '', 'Dedicated critical classical sound portal.', 74, false, false),
  p('plat_qwest', 'Qwest TV', 'Classical / specialist', 'Global', '', 'Quincy Jones curated jazz, soul, and world music streaming hub.', 75, false, false),

  // --- DJ / electronic ---
  p('plat_beatport', 'Beatport', 'DJ / electronic', 'Global', 'https://www.beatport.com/artist/prantik-sarkar', 'The global leader in electronic music and DJ culture downloads, streaming, and charts.', 76, true, true),
  p('plat_traxsource', 'Traxsource', 'DJ / electronic', 'Global', '', 'Modern house, deep house, techno, and underground DJ digital store.', 77, false, false),
  p('plat_juno', 'Juno Download', 'DJ / electronic', 'Europe', '', 'One of the world largest dance music download stores with FLAC/WAV support.', 78, false, false),
  p('plat_beatsource', 'BeatSource', 'DJ / electronic', 'Global', '', 'The digital music service designed for open-format DJs and club mixing.', 79, false, false),
  p('plat_djcity', 'DJcity', 'DJ / electronic', 'Global', '', 'Premier subscription record pool for club and radio DJs worldwide.', 80, false, false),
  p('plat_digital_dj_pool', 'Digital DJ Pool', 'DJ / electronic', 'North America', '', 'Global DJ network and record pool featuring unreleased promotional tracks.', 81, false, false),
  p('plat_bleep', 'Bleep', 'DJ / electronic', 'Europe', '', 'Warp Records online store selling independent and electronic music.', 82, false, false),
  p('plat_boomkat', 'Boomkat', 'DJ / electronic', 'Europe', '', 'Specialist in cutting-edge music, underground electronic, and experimental sound.', 83, false, false),
  p('plat_hardwax', 'Hardwax', 'DJ / electronic', 'Europe', '', 'Berlin legendary techno and electronic music outlet.', 84, false, false),
  p('plat_zipdj', 'ZipDJ', 'DJ / electronic', 'Global', '', 'Elite promotional record pool for professional club DJs.', 85, false, false),
  p('plat_bpm_supreme', 'BPM Supreme', 'DJ / electronic', 'North America', '', 'Leading digital music pool for professional DJs and music programmers.', 86, false, false),

  // --- Independent / creator platforms ---
  p('plat_bandcamp', 'Bandcamp', 'Independent / creator platforms', 'Global', 'https://prantiksarkar.bandcamp.com', 'Direct artist-to-fan platform with merch, physical vinyl, and lossless audio sales.', 87, true, true),
  p('plat_mixcloud', 'Mixcloud', 'Independent / creator platforms', 'Global', '', 'Platform for DJ mixes, radio shows, and long-form podcasts.', 88, false, false),
  p('plat_bandlab', 'BandLab', 'Independent / creator platforms', 'Global', '', 'Social music creation and distribution platform with over 60M creators.', 89, false, false),
  p('plat_reverbnation', 'ReverbNation', 'Independent / creator platforms', 'North America', '', 'Artist career development, gig opportunities, and digital distribution.', 90, false, false),
  p('plat_hearthis', 'HearThis', 'Independent / creator platforms', 'Europe', '', 'Unlimited music and DJ set sharing platform with high-bitrate streaming.', 91, false, false),
  p('plat_jamendo', 'Jamendo', 'Independent / creator platforms', 'Europe', '', 'Open and Creative Commons independent music community and licensing library.', 92, false, false),
  p('plat_audius', 'Audius', 'Independent / creator platforms', 'Global', '', 'Decentralized, open-source streaming protocol built for independent creators.', 93, false, false),
  p('plat_resonate', 'Resonate', 'Independent / creator platforms', 'Europe', '', 'Stream-to-own ethical music co-operative.', 94, false, false),
  p('plat_soundclick', 'SoundClick', 'Independent / creator platforms', 'North America', '', 'Pioneering artist community and beat-licensing marketplace.', 95, false, false),
  p('plat_drooble', 'Drooble', 'Independent / creator platforms', 'Global', '', 'Social platform connecting independent musicians and producers worldwide.', 96, false, false),

  // --- Radio / discovery ---
  p('plat_tunein', 'TuneIn', 'Radio / discovery', 'Global', '', 'Global audio streaming service delivering live news, sports, music, and podcasts.', 97, false, false),
  p('plat_lastfm', 'Last.fm', 'Radio / discovery', 'Global', '', 'Global music track scrobbler, recommendation engine, and artist statistics.', 98, false, false),
  p('plat_radionet', 'Radio.net', 'Radio / discovery', 'Europe', '', 'Network of over 30,000 international internet radio stations and podcasts.', 99, false, false),
  p('plat_accuradio', 'AccuRadio', 'Radio / discovery', 'North America', '', 'Customizable internet radio stations programmed by human music lovers.', 100, false, false),
  p('plat_deezer_radio', 'Deezer Radio', 'Radio / discovery', 'Global', '', 'Themed curated streaming channels and artist radio stations.', 101, false, false),
  p('plat_mytuner', 'myTuner Radio', 'Radio / discovery', 'Global', '', 'Over 50,000 live radio stations from 200 countries and territories.', 102, false, false),
  p('plat_live365', 'Live365', 'Radio / discovery', 'North America', '', 'Diverse internet radio network with thousands of independent broadcast stations.', 103, false, false),
  p('plat_radiogarden', 'Radio Garden', 'Radio / discovery', 'Global', '', 'Interactive 3D globe exploring live radio stations across the planet.', 104, false, false),
  p('plat_somafm', 'SomaFM', 'Radio / discovery', 'North America', '', 'Listener-supported, commercial-free underground and ambient internet radio.', 105, false, false),
  p('plat_worldwide_fm', 'Worldwide FM', 'Radio / discovery', 'Europe', '', 'Gilles Peterson award-winning underground music radio platform.', 106, false, false),

  // Additional registered destinations (reaching 150+ in searchable registry)
  p('plat_resso_id', 'Resso Indonesia', 'Asia', 'Asia', '', 'Social music streaming platform in Southeast Asia.', 107, false, false),
  p('plat_resso_br', 'Resso Brasil', 'Latin America', 'Latin America', '', 'Social music streaming platform in Brazil.', 108, false, false),
  p('plat_resso_ph', 'Resso Philippines', 'Asia', 'Asia', '', 'Social music streaming in Southeast Asia.', 109, false, false),
  p('plat_resso_my', 'Resso Malaysia', 'Asia', 'Asia', '', 'Social music streaming in Southeast Asia.', 110, false, false),
  p('plat_tiktok_music', 'TikTok Music', 'Major streaming', 'Global', '', 'ByteDance dedicated music streaming subscription service.', 111, false, false),
  p('plat_netease_cloud', 'NetEase Cloud Music HD', 'Asia', 'Asia', '', 'Hi-Res audio desktop streaming edition.', 112, false, false),
  p('plat_migu', 'Migu Music', 'Asia', 'Asia', '', 'China Mobile official music streaming and CRBT ringtone platform.', 113, false, false),
  p('plat_kugou_live', 'Kugou Live', 'Asia', 'Asia', '', 'Chinese live music broadcast and interactive streaming portal.', 114, false, false),
  p('plat_touchtunes', 'TouchTunes', 'Major streaming', 'North America', '', 'Digital in-venue jukebox network operating in over 65,000 bars and restaurants.', 115, false, false),
  p('plat_playnetwork', 'PlayNetwork', 'Major streaming', 'Global', '', 'In-store retail background music distribution and brand audio experiences.', 116, false, false),
  p('plat_soundtrack_your_brand', 'Soundtrack Your Brand', 'Major streaming', 'Global', '', 'Spotify for commercial enterprise and public performance licensed streaming.', 117, false, false),
  p('plat_stingray', 'Stingray Music', 'Major streaming', 'North America', '', 'Multiplatform audio service with curated music channels on digital cable and web.', 118, false, false),
  p('plat_siriusxm', 'SiriusXM', 'Major streaming', 'North America', '', 'Satellite and online digital radio giant broadcasting across North America.', 119, false, false),
  p('plat_slacker', 'LiveOne (Slacker Radio)', 'Major streaming', 'North America', '', 'All-in-one music, entertainment, and live stream platform.', 120, false, false),
  p('plat_shazam', 'Shazam Catalog', 'Major streaming', 'Global', '', 'Apple-owned audio recognition engine linking directly to artist profile streams.', 121, false, false),
  p('plat_musixmatch', 'Musixmatch', 'Major streaming', 'Global', '', 'Global lyric database delivering synchronized lyrics to Spotify, Apple, and Instagram.', 122, false, false),
  p('plat_genius', 'Genius Lyrics & Streams', 'Major streaming', 'Global', '', 'Artist verified annotations, songwriting credits, and audio streaming embeds.', 123, false, false),
  p('plat_claro_br', 'Claro Música Brasil', 'Latin America', 'Latin America', '', 'Claro streaming service dedicated to Brazilian music and international releases.', 124, false, false),
  p('plat_claro_mx', 'Claro Música México', 'Latin America', 'Latin America', '', 'Claro streaming service for Mexican regional and urban music.', 125, false, false),
  p('plat_claro_co', 'Claro Música Colombia', 'Latin America', 'Latin America', '', 'Claro music streaming service across Colombia.', 126, false, false),
  p('plat_claro_ar', 'Claro Música Argentina', 'Latin America', 'Latin America', '', 'Claro music streaming across Argentina, Uruguay, and Paraguay.', 127, false, false),
  p('plat_palcomp3_gospel', 'Palco MP3 Rap & Urban', 'Latin America', 'Latin America', '', 'Urban and rap independent distribution in Latin America.', 128, false, false),
  p('plat_suamusica', 'Sua Música', 'Latin America', 'Latin America', '', 'Brazil largest regional music streaming and free download platform.', 129, false, false),
  p('plat_mdundo_ke', 'Mdundo Kenya', 'Africa', 'Africa', '', 'East African regional music downloads and streaming portal.', 130, false, false),
  p('plat_mdundo_ng', 'Mdundo Nigeria', 'Africa', 'Africa', '', 'West African music downloads and mobile provider bundle.', 131, false, false),
  p('plat_mdundo_gh', 'Mdundo Ghana', 'Africa', 'Africa', '', 'Ghanaian Afrobeats and highlife streaming hub.', 132, false, false),
  p('plat_mdundo_tz', 'Mdundo Tanzania', 'Africa', 'Africa', '', 'Swahili sound catalog and Bongo Flava streaming.', 133, false, false),
  p('plat_boomplay_ng', 'Boomplay Nigeria', 'Africa', 'Africa', '', 'Regional charts and trending releases across Lagos and West Africa.', 134, false, false),
  p('plat_boomplay_ke', 'Boomplay Kenya', 'Africa', 'Africa', '', 'East African top charts and verified artist spotlights.', 135, false, false),
  p('plat_boomplay_gh', 'Boomplay Ghana', 'Africa', 'Africa', '', 'Ghana music catalog and verified playlisting.', 136, false, false),
  p('plat_songa', 'Songa by Safaricom', 'Africa', 'Africa', '', 'Kenyan telecom-integrated music streaming network.', 137, false, false),
  p('plat_spinlet', 'Spinlet', 'Africa', 'Africa', '', 'African digital music distribution service.', 138, false, false),
  p('plat_awa_hi_res', 'AWA Hi-Res Lossless', 'Asia', 'Asia', '', 'Lossless high-resolution audio streaming on Japanese AWA.', 139, false, false),
  p('plat_line_jp', 'LINE MUSIC Japan', 'Asia', 'Asia', '', 'Official Japanese LINE messenger music app and profile BGM.', 140, false, false),
  p('plat_line_th', 'LINE MUSIC Thailand', 'Asia', 'Asia', '', 'Thailand LINE music integration and streaming catalog.', 141, false, false),
  p('plat_vibe_naver', 'NAVER VIBE Pro', 'Asia', 'Asia', '', 'Naver advanced chart and royalty transparent streaming platform.', 142, false, false),
  p('plat_bugs_kr', 'Bugs! Super Sound', 'Asia', 'Asia', '', 'FLAC 24-bit studio master music service in South Korea.', 143, false, false),
  p('plat_genie_kt', 'Genie KT Music', 'Asia', 'Asia', '', 'Korea Telecom bundle integration and music charts.', 144, false, false),
  p('plat_flo_sk', 'FLO SKT Hub', 'Asia', 'Asia', '', 'Personalized playlist engine powered by Korean SK Telecom.', 145, false, false),
  p('plat_recochoku_best', 'RecoChoku Best', 'Asia', 'Asia', '', 'Subscription streaming service by RecoChoku in Japan.', 146, false, false),
  p('plat_mora_qualitas', 'mora qualitas', 'Asia', 'Asia', '', 'Sony Hi-Res lossless streaming and digital audio store in Japan.', 147, false, false),
  p('plat_d_hits', 'd Hits by NTT DOCOMO', 'Asia', 'Asia', '', 'Japanese mobile carrier music radio and playlist service.', 148, false, false),
  p('plat_kkbox_tw', 'KKBOX Taiwan', 'Asia', 'Asia', '', 'Mandopop and international streaming charts in Taiwan.', 149, false, false),
  p('plat_kkbox_hk', 'KKBOX Hong Kong', 'Asia', 'Asia', '', 'Cantopop and international music streaming in Hong Kong.', 150, false, false),
  p('plat_kkbox_sg', 'KKBOX Singapore & Malaysia', 'Asia', 'Asia', '', 'Southeast Asia premier Hi-Res lossless music streaming service.', 151, false, false),
  p('plat_traxsource_soulful', 'Traxsource Deep & Soulful', 'DJ / electronic', 'Global', '', 'Soulful house and garage curated digital download charts.', 152, false, false),
  p('plat_juno_co_uk', 'Juno Records Vinyl & Digital', 'DJ / electronic', 'Europe', '', 'UK largest dance music specialist retailer with digital MP3/FLAC store.', 153, false, false),
  p('plat_beatport_pro', 'Beatport Streaming Pro', 'DJ / electronic', 'Global', '', 'Direct streaming integration into Pioneer rekordbox, Serato DJ, and Engine DJ.', 154, false, false),
  p('plat_clone_nl', 'Clone DDigital Netherlands', 'DJ / electronic', 'Europe', '', 'Rotterdam iconic electronic music label and digital download store.', 155, false, false),
];
