import { PaymentGatewayConfig, PaymentSystemSettings, PendingManualPayment } from '../types';

export const DEFAULT_PAYMENT_GATEWAYS: PaymentGatewayConfig[] = [
  {
    id: 'gw_razorpay_live',
    name: 'Razorpay Direct Gateway',
    provider: 'razorpay',
    merchant_id: 'rzp_live_PRANTIK82910',
    secret_key: '••••••••••••••••••••••••',
    webhook_url: 'https://ais-dev-ix3w6hjgbdutkpq7hmowhi-66792404892.asia-southeast1.run.app/api/webhooks/payment/razorpay',
    environment: 'Live',
    currency: 'INR',
    is_enabled: true,
    is_default: true,
    status: 'Active',
    last_tested_at: new Date().toISOString(),
    created_at: new Date('2026-01-01').toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'gw_cashfree_backup',
    name: 'Cashfree Auto-Collect',
    provider: 'cashfree',
    merchant_id: 'cf_app_991823710',
    secret_key: '••••••••••••••••••••••••',
    webhook_url: 'https://ais-dev-ix3w6hjgbdutkpq7hmowhi-66792404892.asia-southeast1.run.app/api/webhooks/payment/cashfree',
    environment: 'Live',
    currency: 'INR',
    is_enabled: true,
    is_default: false,
    status: 'Active',
    last_tested_at: new Date().toISOString(),
    created_at: new Date('2026-01-10').toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'gw_stripe_global',
    name: 'Stripe International (USD/EUR)',
    provider: 'stripe',
    merchant_id: 'acct_1N0982PrantikArtist',
    secret_key: '••••••••••••••••••••••••',
    webhook_url: 'https://ais-dev-ix3w6hjgbdutkpq7hmowhi-66792404892.asia-southeast1.run.app/api/webhooks/payment/stripe',
    environment: 'Test',
    currency: 'USD',
    is_enabled: false,
    is_default: false,
    status: 'Inactive',
    created_at: new Date('2026-02-01').toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEFAULT_PAYMENT_SETTINGS: PaymentSystemSettings = {
  default_gateway_id: 'gw_razorpay_live',
  backup_gateway_id: 'gw_cashfree_backup',
  automatic_failover: true,
  webhook_verification: true,
  realtime_status: true,
  refunds_enabled: true,
  currency: 'INR',
  currency_symbol: '₹',
  tax_percentage: 18,
  receipt_invoice_enabled: true,

  // Manual UPI / QR Fallback
  manual_upi_enabled: true,
  upi_id: 'prantiksarkarartist@upi',
  qr_code_url: 'https://api.qrserver.com/v1/create-qr-code/?size=240x240&data=upi%3A%2F%2Fpay%3Fpa%3Dprantiksarkarartist%40upi%26pn%3DPrantik%20Sarkar%20Artist%26cu%3DINR',
  payment_instructions: 'Scan this QR code using Google Pay, PhonePe, Paytm, BHIM, or any banking UPI app. Enter the total amount and complete payment. Enter your 12-digit UTR / Transaction Reference Number below to submit verification.',
  verification_mode: 'admin_approval',

  // SLA & Non-Refundable Policy
  verification_target_minutes: 30,
  automatic_escalation: true,
  escalate_after_minutes: 30,
  escalation_action: 'Notify Admin Desk & Audit Log',
  auto_refund: false,
  non_refundable_after_verification: true,
  refund_exceptions: [
    'Required by applicable law',
    'Admin-authorized exception',
    'Double deduction / duplicate UTR submission',
  ],
};

export const DEFAULT_PENDING_PAYMENTS: PendingManualPayment[] = [
  {
    id: 'pay_man_1042',
    order_number: 'ORD-1042',
    customer_name: 'Vikram Sengupta',
    customer_email: 'vikram.music@outlook.com',
    amount: 999,
    currency: 'INR',
    payment_method: 'UPI',
    utr_number: '429381920391',
    item_description: 'Single Song Global Distribution (Ditto Worldwide)',
    submitted_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(), // 18 mins ago
    status: 'PENDING_VERIFICATION',
  },
  {
    id: 'pay_man_1041',
    order_number: 'ORD-1041',
    customer_name: 'Ananya Sharma',
    customer_email: 'ananya.producer@gmail.com',
    amount: 4999,
    currency: 'INR',
    payment_method: 'UPI',
    utr_number: '429188203112',
    item_description: 'Official VEVO Channel Setup & Artist Verification',
    submitted_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(), // 42 mins ago (escalated)
    status: 'PENDING_VERIFICATION',
  },
  {
    id: 'pay_man_1039',
    order_number: 'ORD-1039',
    customer_name: 'Rohan Mehra',
    customer_email: 'rohan.beats@yahoo.com',
    amount: 2499,
    currency: 'INR',
    payment_method: 'UPI',
    utr_number: '428810293810',
    item_description: 'Music Video Distribution + Sync Pitching',
    submitted_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    status: 'VERIFIED',
    verified_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    verified_by: 'Prantik Sarkar (Owner)',
    receipt_id: 'RCP-ORD-1039-42881',
  },
];
